import fs from 'fs';

const translations = {
  // Activities.jsx
  act_title: { 'en-US': 'Community Activities', 'bn-BD': 'কমিউনিটি কার্যক্রম', 'hi-IN': 'सामुदायिक गतिविधियाँ', 'ar-SA': 'الأنشطة المجتمعية', 'es-ES': 'Actividades de la Comunidad', 'fr-FR': 'Activités Communautaires', 'pt-BR': 'Atividades da Comunidade', 'ru-RU': 'Общественные мероприятия', 'ur-PK': 'کمیونٹی سرگرمیاں', 'tr-TR': 'Topluluk Etkinlikleri' },
  act_subtitle: { 'en-US': 'Browse, join, and host local physical fitness and networking events.', 'bn-BD': 'স্থানীয় শারীরিক সুস্থতা ও নেটওয়ার্কিং ইভেন্ট ব্রাউজ করুন, যোগ দিন এবং আয়োজন করুন।', 'hi-IN': 'स्थानीय फिटनेस और नेटवर्किंग इवेंट ब्राउज़ करें, ज्वाइन करें और होस्ट करें।', 'ar-SA': 'تصفح الأحداث المحلية للياقة البدنية والتواصل وانضم إليها واستضفها.', 'es-ES': 'Navega, únete y organiza eventos locales de fitness y networking.', 'fr-FR': 'Parcourez, rejoignez et organisez des événements locaux de fitness et de réseautage.', 'pt-BR': 'Navegue, participe e organize eventos locais de fitness e networking.', 'ru-RU': 'Просматривайте, присоединяйтесь и организуйте местные фитнес- и нетворкинг-мероприятия.', 'ur-PK': 'مقامی فٹنس اور نیٹ ورکنگ ایونٹس براؤز کریں، شامل ہوں اور میزبانی کریں۔', 'tr-TR': 'Yerel fitness ve ağ oluşturma etkinliklerini keşfedin, katılın ve düzenleyin.' },
  act_btn_host: { 'en-US': 'Host Activity', 'bn-BD': 'কার্যক্রম আয়োজন করুন', 'hi-IN': 'गतिविधि होस्ट करें', 'ar-SA': 'استضافة نشاط', 'es-ES': 'Organizar Actividad', 'fr-FR': 'Organiser une Activité', 'pt-BR': 'Hospedar Atividade', 'ru-RU': 'Организовать мероприятие', 'ur-PK': 'سرگرمی کی میزبانی', 'tr-TR': 'Etkinlik Düzenle' },
  act_ph_search: { 'en-US': 'Search activities or hosts...', 'bn-BD': 'কার্যক্রম বা আয়োজক খুঁজুন...', 'hi-IN': 'गतिविधियाँ या होस्ट खोजें...', 'ar-SA': 'ابحث عن الأنشطة أو المضيفين...', 'es-ES': 'Buscar actividades o anfitriones...', 'fr-FR': 'Rechercher des activités ou des organisateurs...', 'pt-BR': 'Pesquisar atividades ou anfitriões...', 'ru-RU': 'Поиск мероприятий или организаторов...', 'ur-PK': 'سرگرمیاں یا میزبان تلاش کریں...', 'tr-TR': 'Etkinlik veya organizatör ara...' },
  act_empty_title: { 'en-US': 'No Activities Found', 'bn-BD': 'কোনো কার্যক্রম পাওয়া যায়নি', 'hi-IN': 'कोई गतिविधि नहीं मिली', 'ar-SA': 'لا توجد أنشطة', 'es-ES': 'No se Encontraron Actividades', 'fr-FR': 'Aucune Activité Trouvée', 'pt-BR': 'Nenhuma Atividade Encontrada', 'ru-RU': 'Мероприятия не найдены', 'ur-PK': 'کوئی سرگرمی نہیں ملی', 'tr-TR': 'Etkinlik Bulunamadı' },
  act_empty_hint: { 'en-US': 'Be the first to host one by clicking the "Host Activity" button!', 'bn-BD': '"কার্যক্রম আয়োজন করুন" বোতামে ক্লিক করে প্রথম হয়ে যান!', 'hi-IN': '"गतिविधि होस्ट करें" बटन पर क्लिक करके पहले बनें!', 'ar-SA': 'كن أول من يستضيف نشاطاً بالنقر على زر "استضافة نشاط"!', 'es-ES': '¡Sé el primero en organizar una haciendo clic en el botón "Organizar Actividad"!', 'fr-FR': 'Soyez le premier à en organiser une en cliquant sur le bouton "Organiser une Activité" !', 'pt-BR': 'Seja o primeiro a hospedar clicando no botão "Hospedar Atividade"!', 'ru-RU': 'Будьте первым — нажмите кнопку «Организовать мероприятие»!', 'ur-PK': '"سرگرمی کی میزبانی" بٹن پر کلک کریں اور پہلے بنیں!', 'tr-TR': '"Etkinlik Düzenle" butonuna tıklayarak ilk siz düzenleyin!' },
  act_hosted_by: { 'en-US': 'Hosted by', 'bn-BD': 'আয়োজক', 'hi-IN': 'द्वारा होस्ट', 'ar-SA': 'مستضاف بواسطة', 'es-ES': 'Organizado por', 'fr-FR': 'Organisé par', 'pt-BR': 'Organizado por', 'ru-RU': 'Организатор', 'ur-PK': 'میزبان', 'tr-TR': 'Düzenleyen' },
  act_free: { 'en-US': 'Free', 'bn-BD': 'বিনামূল্যে', 'hi-IN': 'मुफ्त', 'ar-SA': 'مجاني', 'es-ES': 'Gratis', 'fr-FR': 'Gratuit', 'pt-BR': 'Grátis', 'ru-RU': 'Бесплатно', 'ur-PK': 'مفت', 'tr-TR': 'Ücretsiz' },
  act_btn_join: { 'en-US': 'Join', 'bn-BD': 'যোগ দিন', 'hi-IN': 'जॉइन करें', 'ar-SA': 'انضم', 'es-ES': 'Unirse', 'fr-FR': 'Rejoindre', 'pt-BR': 'Participar', 'ru-RU': 'Вступить', 'ur-PK': 'شامل ہوں', 'tr-TR': 'Katıl' },
  act_lbl_date: { 'en-US': 'Date', 'bn-BD': 'তারিখ', 'hi-IN': 'तारीख', 'ar-SA': 'التاريخ', 'es-ES': 'Fecha', 'fr-FR': 'Date', 'pt-BR': 'Data', 'ru-RU': 'Дата', 'ur-PK': 'تاریخ', 'tr-TR': 'Tarih' },
  act_lbl_time: { 'en-US': 'Time', 'bn-BD': 'সময়', 'hi-IN': 'समय', 'ar-SA': 'الوقت', 'es-ES': 'Hora', 'fr-FR': 'Heure', 'pt-BR': 'Hora', 'ru-RU': 'Время', 'ur-PK': 'وقت', 'tr-TR': 'Saat' },
  act_lbl_location: { 'en-US': 'Location', 'bn-BD': 'অবস্থান', 'hi-IN': 'स्थान', 'ar-SA': 'الموقع', 'es-ES': 'Ubicación', 'fr-FR': 'Lieu', 'pt-BR': 'Local', 'ru-RU': 'Место', 'ur-PK': 'مقام', 'tr-TR': 'Konum' },
  act_lbl_participants: { 'en-US': 'Participants', 'bn-BD': 'অংশগ্রহণকারী', 'hi-IN': 'प्रतिभागी', 'ar-SA': 'المشاركون', 'es-ES': 'Participantes', 'fr-FR': 'Participants', 'pt-BR': 'Participantes', 'ru-RU': 'Участники', 'ur-PK': 'شرکاء', 'tr-TR': 'Katılımcılar' },
  act_joined: { 'en-US': 'Joined', 'bn-BD': 'যোগ দিয়েছেন', 'hi-IN': 'शामिल', 'ar-SA': 'انضم', 'es-ES': 'Inscrito', 'fr-FR': 'Inscrit', 'pt-BR': 'Inscrito', 'ru-RU': 'Вступил', 'ur-PK': 'شامل', 'tr-TR': 'Katıldı' },
  act_entry_fee: { 'en-US': 'Entry Fee', 'bn-BD': 'প্রবেশ মূল্য', 'hi-IN': 'प्रवेश शुल्क', 'ar-SA': 'رسوم الدخول', 'es-ES': 'Tarifa de Entrada', 'fr-FR': 'Frais d\'entrée', 'pt-BR': 'Taxa de Entrada', 'ru-RU': 'Вступительный взнос', 'ur-PK': 'داخلہ فیس', 'tr-TR': 'Giriş Ücreti' },
  act_btn_cancel: { 'en-US': 'Cancel', 'bn-BD': 'বাতিল', 'hi-IN': 'रद्द करें', 'ar-SA': 'إلغاء', 'es-ES': 'Cancelar', 'fr-FR': 'Annuler', 'pt-BR': 'Cancelar', 'ru-RU': 'Отмена', 'ur-PK': 'منسوخ', 'tr-TR': 'İptal' },
  act_btn_confirm_join: { 'en-US': 'Confirm & Join', 'bn-BD': 'নিশ্চিত করুন ও যোগ দিন', 'hi-IN': 'पुष्टि करें और जॉइन करें', 'ar-SA': 'تأكيد والانضمام', 'es-ES': 'Confirmar y Unirse', 'fr-FR': 'Confirmer et Rejoindre', 'pt-BR': 'Confirmar e Participar', 'ru-RU': 'Подтвердить и вступить', 'ur-PK': 'تصدیق کریں اور شامل ہوں', 'tr-TR': 'Onayla ve Katıl' },
  act_modal_host_title: { 'en-US': 'Host Community Activity', 'bn-BD': 'কমিউনিটি কার্যক্রম আয়োজন করুন', 'hi-IN': 'सामुदायिक गतिविधि होस्ट करें', 'ar-SA': 'استضافة نشاط مجتمعي', 'es-ES': 'Organizar Actividad Comunitaria', 'fr-FR': 'Organiser une Activité Communautaire', 'pt-BR': 'Hospedar Atividade Comunitária', 'ru-RU': 'Организовать общественное мероприятие', 'ur-PK': 'کمیونٹی سرگرمی کی میزبانی', 'tr-TR': 'Topluluk Etkinliği Düzenle' },
  act_modal_host_sub: { 'en-US': 'Fill out the information below to schedule and publish your session.', 'bn-BD': 'আপনার সেশন সময়সূচী করতে এবং প্রকাশ করতে নিচের তথ্য পূরণ করুন।', 'hi-IN': 'अपना सत्र शेड्यूल और प्रकाशित करने के लिए नीचे जानकारी भरें।', 'ar-SA': 'أكمل المعلومات أدناه لجدولة جلستك ونشرها.', 'es-ES': 'Completa la información a continuación para programar y publicar tu sesión.', 'fr-FR': 'Remplissez les informations ci-dessous pour programmer et publier votre session.', 'pt-BR': 'Preencha as informações abaixo para agendar e publicar sua sessão.', 'ru-RU': 'Заполните информацию ниже, чтобы запланировать и опубликовать вашу сессию.', 'ur-PK': 'اپنا سیشن شیڈول اور شائع کرنے کے لیے نیچے معلومات پُر کریں۔', 'tr-TR': 'Oturumunuzu planlamak ve yayınlamak için aşağıdaki bilgileri doldurun.' },
  act_lbl_activity_title: { 'en-US': 'Activity Title *', 'bn-BD': 'কার্যক্রমের শিরোনাম *', 'hi-IN': 'गतिविधि शीर्षक *', 'ar-SA': 'عنوان النشاط *', 'es-ES': 'Título de la Actividad *', 'fr-FR': 'Titre de l\'Activité *', 'pt-BR': 'Título da Atividade *', 'ru-RU': 'Название мероприятия *', 'ur-PK': 'سرگرمی کا عنوان *', 'tr-TR': 'Etkinlik Başlığı *' },
  act_ph_title: { 'en-US': 'e.g. Evening Running / Cycling Session', 'bn-BD': 'যেমন: সন্ধ্যায় দৌড়/সাইকেল সেশন', 'hi-IN': 'जैसे: शाम की दौड़/साइकिलिंग सत्र', 'ar-SA': 'مثال: جلسة ركض / دراجات مسائية', 'es-ES': 'ej. Sesión de Running / Ciclismo Vespertino', 'fr-FR': 'ex. Session de Course / Cyclisme en Soirée', 'pt-BR': 'ex. Sessão de Corrida/Ciclismo Noturna', 'ru-RU': 'напр. Вечерняя пробежка/велопрогулка', 'ur-PK': 'مثلاً: شام کی دوڑ / سائیکلنگ سیشن', 'tr-TR': 'örn. Akşam Koşusu / Bisiklet Oturumu' },
  act_lbl_category: { 'en-US': 'Category *', 'bn-BD': 'বিভাগ *', 'hi-IN': 'श्रेणी *', 'ar-SA': 'الفئة *', 'es-ES': 'Categoría *', 'fr-FR': 'Catégorie *', 'pt-BR': 'Categoria *', 'ru-RU': 'Категория *', 'ur-PK': 'زمرہ *', 'tr-TR': 'Kategori *' },
  act_lbl_participant_limit: { 'en-US': 'Participant Limit', 'bn-BD': 'অংশগ্রহণকারী সীমা', 'hi-IN': 'प्रतिभागी सीमा', 'ar-SA': 'حد المشاركين', 'es-ES': 'Límite de Participantes', 'fr-FR': 'Limite de Participants', 'pt-BR': 'Limite de Participantes', 'ru-RU': 'Лимит участников', 'ur-PK': 'شرکاء کی حد', 'tr-TR': 'Katılımcı Limiti' },
  act_lbl_description: { 'en-US': 'Description', 'bn-BD': 'বিবরণ', 'hi-IN': 'विवरण', 'ar-SA': 'الوصف', 'es-ES': 'Descripción', 'fr-FR': 'Description', 'pt-BR': 'Descrição', 'ru-RU': 'Описание', 'ur-PK': 'تفصیل', 'tr-TR': 'Açıklama' },
  act_ph_description: { 'en-US': 'Describe the fitness session goals, pace, target participants, etc.', 'bn-BD': 'ফিটনেস সেশনের লক্ষ্য, গতি, লক্ষ্য অংশগ্রহণকারী ইত্যাদি বর্ণনা করুন।', 'hi-IN': 'फिटनेस सत्र के लक्ष्य, गति, लक्षित प्रतिभागी आदि का वर्णन करें।', 'ar-SA': 'صف أهداف جلسة اللياقة والوتيرة والمشاركين المستهدفين وما إلى ذلك.', 'es-ES': 'Describe los objetivos de la sesión de fitness, el ritmo, los participantes objetivo, etc.', 'fr-FR': 'Décrivez les objectifs de la séance de fitness, le rythme, les participants cibles, etc.', 'pt-BR': 'Descreva os objetivos da sessão de fitness, ritmo, participantes-alvo, etc.', 'ru-RU': 'Опишите цели фитнес-сессии, темп, целевых участников и т.д.', 'ur-PK': 'فٹنس سیشن کے اہداف، رفتار، ہدف شرکاء وغیرہ بیان کریں۔', 'tr-TR': 'Fitness oturumunun hedeflerini, temposunu, hedef katılımcıları vb. açıklayın.' },
  act_lbl_location_addr: { 'en-US': 'Location Address *', 'bn-BD': 'অবস্থানের ঠিকানা *', 'hi-IN': 'स्थान का पता *', 'ar-SA': 'عنوان الموقع *', 'es-ES': 'Dirección de Ubicación *', 'fr-FR': 'Adresse du Lieu *', 'pt-BR': 'Endereço do Local *', 'ru-RU': 'Адрес места *', 'ur-PK': 'مقام کا پتہ *', 'tr-TR': 'Konum Adresi *' },
  act_ph_location: { 'en-US': 'e.g. Greenwood Park Main Gate', 'bn-BD': 'যেমন: গ্রিনউড পার্ক মেইন গেট', 'hi-IN': 'जैसे: ग्रीनवुड पार्क मुख्य द्वार', 'ar-SA': 'مثال: البوابة الرئيسية لحديقة غرينوود', 'es-ES': 'ej. Puerta Principal del Parque Greenwood', 'fr-FR': 'ex. Porte Principale du Parc Greenwood', 'pt-BR': 'ex. Portão Principal do Parque Greenwood', 'ru-RU': 'напр. Главный вход в парк Гринвуд', 'ur-PK': 'مثلاً: گرین وڈ پارک مین گیٹ', 'tr-TR': 'örn. Greenwood Parkı Ana Kapısı' },
  act_lbl_date_field: { 'en-US': 'Date *', 'bn-BD': 'তারিখ *', 'hi-IN': 'तारीख *', 'ar-SA': 'التاريخ *', 'es-ES': 'Fecha *', 'fr-FR': 'Date *', 'pt-BR': 'Data *', 'ru-RU': 'Дата *', 'ur-PK': 'تاریخ *', 'tr-TR': 'Tarih *' },
  act_ph_date: { 'en-US': 'e.g. June 24, 2026', 'bn-BD': 'যেমন: ২৪ জুন, ২০২৬', 'hi-IN': 'जैसे: 24 जून, 2026', 'ar-SA': 'مثال: 24 يونيو 2026', 'es-ES': 'ej. 24 de junio de 2026', 'fr-FR': 'ex. 24 juin 2026', 'pt-BR': 'ex. 24 de junho de 2026', 'ru-RU': 'напр. 24 июня 2026', 'ur-PK': 'مثلاً: 24 جون 2026', 'tr-TR': 'örn. 24 Haziran 2026' },
  act_lbl_time_field: { 'en-US': 'Time *', 'bn-BD': 'সময় *', 'hi-IN': 'समय *', 'ar-SA': 'الوقت *', 'es-ES': 'Hora *', 'fr-FR': 'Heure *', 'pt-BR': 'Hora *', 'ru-RU': 'Время *', 'ur-PK': 'وقت *', 'tr-TR': 'Saat *' },
  act_ph_time: { 'en-US': 'e.g. 7:00 AM', 'bn-BD': 'যেমন: সকাল ৭:০০', 'hi-IN': 'जैसे: सुबह 7:00', 'ar-SA': 'مثال: 7:00 صباحاً', 'es-ES': 'ej. 7:00 AM', 'fr-FR': 'ex. 7h00', 'pt-BR': 'ex. 7:00 da manhã', 'ru-RU': 'напр. 7:00 утра', 'ur-PK': 'مثلاً: صبح 7:00', 'tr-TR': 'örn. 7:00' },
  act_lbl_price: { 'en-US': 'Entry Price ($)', 'bn-BD': 'প্রবেশ মূল্য ($)', 'hi-IN': 'प्रवेश मूल्य ($)', 'ar-SA': 'سعر الدخول ($)', 'es-ES': 'Precio de Entrada ($)', 'fr-FR': 'Prix d\'Entrée ($)', 'pt-BR': 'Preço de Entrada ($)', 'ru-RU': 'Стоимость входа ($)', 'ur-PK': 'داخلہ قیمت ($)', 'tr-TR': 'Giriş Ücreti ($)' },
  act_btn_publish: { 'en-US': 'Publish Activity', 'bn-BD': 'কার্যক্রম প্রকাশ করুন', 'hi-IN': 'गतिविधि प्रकाशित करें', 'ar-SA': 'نشر النشاط', 'es-ES': 'Publicar Actividad', 'fr-FR': 'Publier l\'Activité', 'pt-BR': 'Publicar Atividade', 'ru-RU': 'Опубликовать мероприятие', 'ur-PK': 'سرگرمی شائع کریں', 'tr-TR': 'Etkinliği Yayınla' },
  act_err_required_fields: { 'en-US': 'Please fill in all required fields.', 'bn-BD': 'অনুগ্রহ করে সমস্ত প্রয়োজনীয় ক্ষেত্র পূরণ করুন।', 'hi-IN': 'कृपया सभी आवश्यक फ़ील्ड भरें।', 'ar-SA': 'يرجى ملء جميع الحقول المطلوبة.', 'es-ES': 'Por favor, completa todos los campos obligatorios.', 'fr-FR': 'Veuillez remplir tous les champs obligatoires.', 'pt-BR': 'Por favor, preencha todos os campos obrigatórios.', 'ru-RU': 'Пожалуйста, заполните все обязательные поля.', 'ur-PK': 'براہ کرم تمام مطلوبہ خانے پُر کریں۔', 'tr-TR': 'Lütfen tüm gerekli alanları doldurun.' },
  act_success_joined: { 'en-US': 'Successfully joined the activity! Get ready to meet your fitness partners.', 'bn-BD': 'সফলভাবে কার্যক্রমে যোগ দেওয়া হয়েছে! আপনার ফিটনেস অংশীদারদের সাথে দেখা করার জন্য প্রস্তুত হন।', 'hi-IN': 'गतिविधि में सफलतापूर्वक शामिल हुए! अपने फिटनेस पार्टनर से मिलने के लिए तैयार हों।', 'ar-SA': 'تم الانضمام إلى النشاط بنجاح! استعد للقاء شركاء اللياقة البدنية.', 'es-ES': '¡Te has unido a la actividad con éxito! Prepárate para conocer a tus compañeros de fitness.', 'fr-FR': 'Vous avez rejoint l\'activité avec succès ! Préparez-vous à rencontrer vos partenaires de fitness.', 'pt-BR': 'Participação na atividade bem-sucedida! Prepare-se para conhecer seus parceiros de fitness.', 'ru-RU': 'Вы успешно вступили в мероприятие! Готовьтесь познакомиться со своими партнёрами по фитнесу.', 'ur-PK': 'سرگرمی میں کامیابی سے شامل ہو گئے! اپنے فٹنس پارٹنرز سے ملنے کے لیے تیار ہوں۔', 'tr-TR': 'Etkinliğe başarıyla katıldınız! Fitness ortaklarınızla tanışmaya hazır olun.' },
  act_err_join: { 'en-US': 'Could not join activity.', 'bn-BD': 'কার্যক্রমে যোগ দেওয়া যায়নি।', 'hi-IN': 'गतिविधि में शामिल नहीं हो सके।', 'ar-SA': 'تعذر الانضمام إلى النشاط.', 'es-ES': 'No se pudo unir a la actividad.', 'fr-FR': 'Impossible de rejoindre l\'activité.', 'pt-BR': 'Não foi possível participar da atividade.', 'ru-RU': 'Не удалось вступить в мероприятие.', 'ur-PK': 'سرگرمی میں شامل نہیں ہو سکے۔', 'tr-TR': 'Etkinliğe katılınamadı.' },
  act_success_hosted: { 'en-US': 'Activity hosted successfully! Event is now visible in the community feed.', 'bn-BD': 'কার্যক্রম সফলভাবে আয়োজিত হয়েছে! ইভেন্টটি এখন কমিউনিটি ফিডে দৃশ্যমান।', 'hi-IN': 'गतिविधि सफलतापूर्वक होस्ट की गई! इवेंट अब सामुदायिक फ़ीड में दिखाई देता है।', 'ar-SA': 'تمت استضافة النشاط بنجاح! الحدث مرئي الآن في خلاصة المجتمع.', 'es-ES': '¡Actividad publicada con éxito! El evento ahora es visible en el feed de la comunidad.', 'fr-FR': 'Activité organisée avec succès ! L\'événement est maintenant visible dans le fil communautaire.', 'pt-BR': 'Atividade publicada com sucesso! O evento agora está visível no feed da comunidade.', 'ru-RU': 'Мероприятие успешно опубликовано! Теперь оно отображается в общей ленте.', 'ur-PK': 'سرگرمی کامیابی سے شائع ہو گئی! ایونٹ اب کمیونٹی فیڈ میں نظر آ رہا ہے۔', 'tr-TR': 'Etkinlik başarıyla yayınlandı! Etkinlik artık topluluk akışında görünüyor.' },
  act_err_host: { 'en-US': 'Could not host activity.', 'bn-BD': 'কার্যক্রম আয়োজন করা যায়নি।', 'hi-IN': 'गतिविधि होस्ट नहीं की जा सकी।', 'ar-SA': 'تعذر استضافة النشاط.', 'es-ES': 'No se pudo organizar la actividad.', 'fr-FR': 'Impossible d\'organiser l\'activité.', 'pt-BR': 'Não foi possível hospedar a atividade.', 'ru-RU': 'Не удалось организовать мероприятие.', 'ur-PK': 'سرگرمی کی میزبانی نہیں کی جا سکی۔', 'tr-TR': 'Etkinlik düzenlenemedi.' },
  act_cat_all: { 'en-US': 'All Activities', 'bn-BD': 'সকল কার্যক্রম', 'hi-IN': 'सभी गतिविधियाँ', 'ar-SA': 'جميع الأنشطة', 'es-ES': 'Todas las Actividades', 'fr-FR': 'Toutes les Activités', 'pt-BR': 'Todas as Atividades', 'ru-RU': 'Все мероприятия', 'ur-PK': 'تمام سرگرمیاں', 'tr-TR': 'Tüm Etkinlikler' },

  // ContentPage.jsx
  content_btn_back: { 'en-US': 'Back to Home', 'bn-BD': 'হোমে ফিরুন', 'hi-IN': 'होम पर वापस जाएं', 'ar-SA': 'العودة إلى الرئيسية', 'es-ES': 'Volver al Inicio', 'fr-FR': 'Retour à l\'accueil', 'pt-BR': 'Voltar ao Início', 'ru-RU': 'На главную', 'ur-PK': 'ہوم پر واپس', 'tr-TR': 'Ana Sayfaya Dön' },
  content_alt_logo: { 'en-US': 'GoCustify logo', 'bn-BD': 'GoCustify লোগো', 'hi-IN': 'GoCustify लोगो', 'ar-SA': 'شعار GoCustify', 'es-ES': 'Logo de GoCustify', 'fr-FR': 'Logo GoCustify', 'pt-BR': 'Logo do GoCustify', 'ru-RU': 'Логотип GoCustify', 'ur-PK': 'GoCustify لوگو', 'tr-TR': 'GoCustify logosu' },
  content_err_load: { 'en-US': 'Could not load this page.', 'bn-BD': 'এই পৃষ্ঠাটি লোড করা যায়নি।', 'hi-IN': 'यह पृष्ठ लोड नहीं हो सका।', 'ar-SA': 'تعذر تحميل هذه الصفحة.', 'es-ES': 'No se pudo cargar esta página.', 'fr-FR': 'Impossible de charger cette page.', 'pt-BR': 'Não foi possível carregar esta página.', 'ru-RU': 'Не удалось загрузить эту страницу.', 'ur-PK': 'یہ صفحہ لوڈ نہیں ہو سکا۔', 'tr-TR': 'Bu sayfa yüklenemedi.' },
  content_updated: { 'en-US': 'Updated', 'bn-BD': 'আপডেট হয়েছে', 'hi-IN': 'अपडेट किया गया', 'ar-SA': 'تم التحديث', 'es-ES': 'Actualizado', 'fr-FR': 'Mis à jour', 'pt-BR': 'Atualizado', 'ru-RU': 'Обновлено', 'ur-PK': 'اپ ڈیٹ ہوا', 'tr-TR': 'Güncellendi' },

  // AiCall.jsx
  aicall_agent_name: { 'en-US': 'Mabdel AI', 'bn-BD': 'Mabdel AI', 'hi-IN': 'Mabdel AI', 'ar-SA': 'Mabdel AI', 'es-ES': 'Mabdel AI', 'fr-FR': 'Mabdel AI', 'pt-BR': 'Mabdel AI', 'ru-RU': 'Mabdel AI', 'ur-PK': 'Mabdel AI', 'tr-TR': 'Mabdel AI' },
  aicall_connecting: { 'en-US': 'Connecting...', 'bn-BD': 'সংযুক্ত হচ্ছে...', 'hi-IN': 'कनेक्ट हो रहा है...', 'ar-SA': 'جارٍ الاتصال...', 'es-ES': 'Conectando...', 'fr-FR': 'Connexion...', 'pt-BR': 'Conectando...', 'ru-RU': 'Подключение...', 'ur-PK': 'جوڑ رہا ہے...', 'tr-TR': 'Bağlanıyor...' },
  aicall_ready: { 'en-US': 'Ready for your call', 'bn-BD': 'আপনার কলের জন্য প্রস্তুত', 'hi-IN': 'आपकी कॉल के लिए तैयार', 'ar-SA': 'جاهز لمكالمتك', 'es-ES': 'Listo para tu llamada', 'fr-FR': 'Prêt pour votre appel', 'pt-BR': 'Pronto para sua ligação', 'ru-RU': 'Готов к звонку', 'ur-PK': 'آپ کی کال کے لیے تیار', 'tr-TR': 'Aramanız için hazır' },
  aicall_err_mic: { 'en-US': 'Microphone access denied. Please allow microphone permissions to make AI Calls.', 'bn-BD': 'মাইক্রোফোন অ্যাক্সেস অস্বীকৃত। AI কল করতে মাইক্রোফোন অনুমতি দিন।', 'hi-IN': 'माइक्रोफ़ोन एक्सेस अस्वीकृत। AI कॉल करने के लिए माइक्रोफ़ोन अनुमति दें।', 'ar-SA': 'تم رفض الوصول إلى الميكروفون. يرجى السماح بأذونات الميكروفون لإجراء مكالمات AI.', 'es-ES': 'Acceso al micrófono denegado. Por favor, permite el acceso al micrófono para hacer llamadas AI.', 'fr-FR': 'Accès au microphone refusé. Veuillez autoriser les permissions du microphone pour effectuer des appels IA.', 'pt-BR': 'Acesso ao microfone negado. Por favor, permita as permissões do microfone para fazer chamadas AI.', 'ru-RU': 'Доступ к микрофону запрещён. Разрешите доступ к микрофону для звонков AI.', 'ur-PK': 'مائیکروفون تک رسائی مسترد۔ AI کالز کے لیے مائیکروفون کی اجازت دیں۔', 'tr-TR': 'Mikrofon erişimi reddedildi. AI aramaları yapmak için mikrofon izinlerine izin verin.' },

  // CreatePost.jsx
  post_title: { 'en-US': 'Create Post', 'bn-BD': 'পোস্ট তৈরি করুন', 'hi-IN': 'पोस्ट बनाएं', 'ar-SA': 'إنشاء منشور', 'es-ES': 'Crear Publicación', 'fr-FR': 'Créer une Publication', 'pt-BR': 'Criar Publicação', 'ru-RU': 'Создать публикацию', 'ur-PK': 'پوسٹ بنائیں', 'tr-TR': 'Gönderi Oluştur' },
  post_subtitle: { 'en-US': 'Generate with AI and publish only to currently connected providers that the backend can actually post to.', 'bn-BD': 'AI দিয়ে তৈরি করুন এবং শুধুমাত্র সংযুক্ত প্রদানকারীদের কাছে প্রকাশ করুন।', 'hi-IN': 'AI से जनरेट करें और केवल वर्तमान में जुड़े प्रदाताओं पर प्रकाशित करें।', 'ar-SA': 'أنشئ باستخدام الذكاء الاصطناعي وانشر فقط على مزودي الخدمة المتصلين حالياً.', 'es-ES': 'Genera con IA y publica solo en los proveedores conectados actualmente.', 'fr-FR': 'Générez avec l\'IA et publiez uniquement sur les fournisseurs actuellement connectés.', 'pt-BR': 'Gere com IA e publique apenas nos provedores conectados atualmente.', 'ru-RU': 'Создавайте с помощью ИИ и публикуйте только в подключённых провайдерах.', 'ur-PK': 'AI سے بنائیں اور صرف موجودہ جڑے ہوئے فراہم کنندگان پر شائع کریں۔', 'tr-TR': 'AI ile oluşturun ve yalnızca şu anda bağlı sağlayıcılara yayınlayın.' },
  post_unsupported_platforms: { 'en-US': 'Connected but unavailable for posting:', 'bn-BD': 'সংযুক্ত কিন্তু পোস্টের জন্য অনুপলব্ধ:', 'hi-IN': 'जुड़ा है लेकिन पोस्ट के लिए अनुपलब्ध:', 'ar-SA': 'متصل ولكن غير متاح للنشر:', 'es-ES': 'Conectado pero no disponible para publicar:', 'fr-FR': 'Connecté mais non disponible pour la publication :', 'pt-BR': 'Conectado mas indisponível para publicação:', 'ru-RU': 'Подключено, но недоступно для публикации:', 'ur-PK': 'جڑا ہوا لیکن پوسٹنگ کے لیے دستیاب نہیں:', 'tr-TR': 'Bağlı ancak gönderi için kullanılamaz:' },
  post_no_publishable: { 'en-US': 'No supported connected social publishing accounts are available for this organization yet.', 'bn-BD': 'এই সংস্থার জন্য এখনও কোনো সমর্থিত সংযুক্ত সামাজিক প্রকাশনা অ্যাকাউন্ট উপলব্ধ নেই।', 'hi-IN': 'इस संगठन के लिए अभी कोई समर्थित कनेक्टेड सोशल प्रकाशन खाता उपलब्ध नहीं है।', 'ar-SA': 'لا تتوفر حسابات نشر اجتماعية متصلة ومدعومة لهذه المؤسسة بعد.', 'es-ES': 'Aún no hay cuentas de publicación social conectadas y compatibles disponibles para esta organización.', 'fr-FR': 'Aucun compte de publication sociale connecté et pris en charge n\'est encore disponible pour cette organisation.', 'pt-BR': 'Nenhuma conta de publicação social conectada e suportada está disponível para esta organização ainda.', 'ru-RU': 'Для этой организации пока нет доступных подключённых социальных аккаунтов для публикации.', 'ur-PK': 'اس تنظیم کے لیے ابھی کوئی معاون سوشل پبلشنگ اکاؤنٹ دستیاب نہیں۔', 'tr-TR': 'Bu kuruluş için henüz desteklenen bağlı sosyal yayın hesabı bulunmuyor.' },
  post_hdr_ai_generator: { 'en-US': 'AI Generator', 'bn-BD': 'AI জেনারেটর', 'hi-IN': 'AI जेनरेटर', 'ar-SA': 'مولّد الذكاء الاصطناعي', 'es-ES': 'Generador AI', 'fr-FR': 'Générateur IA', 'pt-BR': 'Gerador IA', 'ru-RU': 'ИИ-генератор', 'ur-PK': 'AI جنریٹر', 'tr-TR': 'AI Üreteci' },
  post_lbl_prompt: { 'en-US': 'Prompt', 'bn-BD': 'প্রম্পট', 'hi-IN': 'प्रॉम्प्ट', 'ar-SA': 'الأمر', 'es-ES': 'Indicación', 'fr-FR': 'Invite', 'pt-BR': 'Prompt', 'ru-RU': 'Запрос', 'ur-PK': 'پرامپٹ', 'tr-TR': 'İstem' },
  post_ph_prompt: { 'en-US': 'Describe the post you want GoCustify AI to create...', 'bn-BD': 'GoCustify AI দিয়ে কোন পোস্ট তৈরি করতে চান তা বর্ণনা করুন...', 'hi-IN': 'वह पोस्ट बताएं जो आप GoCustify AI से बनाना चाहते हैं...', 'ar-SA': 'صف المنشور الذي تريد من GoCustify AI إنشاءه...', 'es-ES': 'Describe la publicación que quieres que GoCustify AI cree...', 'fr-FR': 'Décrivez la publication que vous souhaitez que GoCustify IA crée...', 'pt-BR': 'Descreva a publicação que você quer que o GoCustify AI crie...', 'ru-RU': 'Опишите публикацию, которую хотите создать с помощью GoCustify AI...', 'ur-PK': 'وہ پوسٹ بیان کریں جو آپ GoCustify AI سے بنانا چاہتے ہیں...', 'tr-TR': 'GoCustify AI\'nın oluşturmasını istediğiniz gönderiyi tanımlayın...' },
  post_btn_generate: { 'en-US': 'Generate Post', 'bn-BD': 'পোস্ট তৈরি করুন', 'hi-IN': 'पोस्ट जनरेट करें', 'ar-SA': 'إنشاء المنشور', 'es-ES': 'Generar Publicación', 'fr-FR': 'Générer la Publication', 'pt-BR': 'Gerar Publicação', 'ru-RU': 'Создать публикацию', 'ur-PK': 'پوسٹ بنائیں', 'tr-TR': 'Gönderi Oluştur' },
  post_hdr_content: { 'en-US': 'Content', 'bn-BD': 'বিষয়বস্তু', 'hi-IN': 'सामग्री', 'ar-SA': 'المحتوى', 'es-ES': 'Contenido', 'fr-FR': 'Contenu', 'pt-BR': 'Conteúdo', 'ru-RU': 'Содержание', 'ur-PK': 'مواد', 'tr-TR': 'İçerik' },
  post_char_count: { 'en-US': '{count} characters', 'bn-BD': '{count} অক্ষর', 'hi-IN': '{count} अक्षर', 'ar-SA': '{count} حرف', 'es-ES': '{count} caracteres', 'fr-FR': '{count} caractères', 'pt-BR': '{count} caracteres', 'ru-RU': '{count} символов', 'ur-PK': '{count} حروف', 'tr-TR': '{count} karakter' },
  post_ph_content: { 'en-US': 'Your final post content appears here...', 'bn-BD': 'আপনার চূড়ান্ত পোস্ট বিষয়বস্তু এখানে প্রদর্শিত হবে...', 'hi-IN': 'आपकी अंतिम पोस्ट सामग्री यहां दिखाई देगी...', 'ar-SA': 'يظهر هنا محتوى منشورك النهائي...', 'es-ES': 'El contenido final de tu publicación aparece aquí...', 'fr-FR': 'Le contenu final de votre publication apparaît ici...', 'pt-BR': 'O conteúdo final da sua publicação aparece aqui...', 'ru-RU': 'Здесь появится финальное содержание вашей публикации...', 'ur-PK': 'آپ کی حتمی پوسٹ کا مواد یہاں ظاہر ہوگا...', 'tr-TR': 'Son gönderi içeriğiniz burada görünür...' },
  post_lbl_platforms: { 'en-US': 'Connected Platforms', 'bn-BD': 'সংযুক্ত প্ল্যাটফর্ম', 'hi-IN': 'जुड़े प्लेटफ़ॉर्म', 'ar-SA': 'المنصات المتصلة', 'es-ES': 'Plataformas Conectadas', 'fr-FR': 'Plateformes Connectées', 'pt-BR': 'Plataformas Conectadas', 'ru-RU': 'Подключённые платформы', 'ur-PK': 'جڑے ہوئے پلیٹ فارم', 'tr-TR': 'Bağlı Platformlar' },
  post_loading_accounts: { 'en-US': 'Loading connected accounts...', 'bn-BD': 'সংযুক্ত অ্যাকাউন্ট লোড হচ্ছে...', 'hi-IN': 'जुड़े अकाउंट लोड हो रहे हैं...', 'ar-SA': 'جارٍ تحميل الحسابات المتصلة...', 'es-ES': 'Cargando cuentas conectadas...', 'fr-FR': 'Chargement des comptes connectés...', 'pt-BR': 'Carregando contas conectadas...', 'ru-RU': 'Загрузка подключённых аккаунтов...', 'ur-PK': 'جڑے ہوئے اکاؤنٹ لوڈ ہو رہے ہیں...', 'tr-TR': 'Bağlı hesaplar yükleniyor...' },
  post_no_platforms: { 'en-US': 'No publishable connected platforms found.', 'bn-BD': 'কোনো প্রকাশযোগ্য সংযুক্ত প্ল্যাটফর্ম পাওয়া যায়নি।', 'hi-IN': 'कोई प्रकाशनयोग्य जुड़ा प्लेटफ़ॉर्म नहीं मिला।', 'ar-SA': 'لم يتم العثور على منصات متصلة قابلة للنشر.', 'es-ES': 'No se encontraron plataformas conectadas publicables.', 'fr-FR': 'Aucune plateforme connectée publiable trouvée.', 'pt-BR': 'Nenhuma plataforma conectada publicável encontrada.', 'ru-RU': 'Подключённые платформы для публикации не найдены.', 'ur-PK': 'کوئی قابل اشاعت جڑا ہوا پلیٹ فارم نہیں ملا۔', 'tr-TR': 'Yayınlanabilir bağlı platform bulunamadı.' },
  post_lbl_schedule: { 'en-US': 'Schedule Date', 'bn-BD': 'সময়সূচী তারিখ', 'hi-IN': 'शेड्यूल तारीख', 'ar-SA': 'تاريخ الجدولة', 'es-ES': 'Fecha de Programación', 'fr-FR': 'Date de Programmation', 'pt-BR': 'Data de Agendamento', 'ru-RU': 'Дата публикации', 'ur-PK': 'شیڈول تاریخ', 'tr-TR': 'Zamanlama Tarihi' },
  post_btn_publish: { 'en-US': 'Publish Now', 'bn-BD': 'এখনই প্রকাশ করুন', 'hi-IN': 'अभी प्रकाशित करें', 'ar-SA': 'نشر الآن', 'es-ES': 'Publicar Ahora', 'fr-FR': 'Publier Maintenant', 'pt-BR': 'Publicar Agora', 'ru-RU': 'Опубликовать сейчас', 'ur-PK': 'ابھی شائع کریں', 'tr-TR': 'Şimdi Yayınla' },
  post_btn_schedule: { 'en-US': 'Schedule', 'bn-BD': 'সময়সূচী করুন', 'hi-IN': 'शेड्यूल करें', 'ar-SA': 'جدولة', 'es-ES': 'Programar', 'fr-FR': 'Programmer', 'pt-BR': 'Agendar', 'ru-RU': 'Запланировать', 'ur-PK': 'شیڈول', 'tr-TR': 'Zamanla' },
  post_hdr_recent: { 'en-US': 'Recent Posts', 'bn-BD': 'সাম্প্রতিক পোস্ট', 'hi-IN': 'हाल की पोस्ट', 'ar-SA': 'المنشورات الأخيرة', 'es-ES': 'Publicaciones Recientes', 'fr-FR': 'Publications Récentes', 'pt-BR': 'Publicações Recentes', 'ru-RU': 'Последние публикации', 'ur-PK': 'حالیہ پوسٹس', 'tr-TR': 'Son Gönderiler' },
  post_btn_refresh: { 'en-US': 'Refresh', 'bn-BD': 'রিফ্রেশ করুন', 'hi-IN': 'रिफ्रेश करें', 'ar-SA': 'تحديث', 'es-ES': 'Actualizar', 'fr-FR': 'Actualiser', 'pt-BR': 'Atualizar', 'ru-RU': 'Обновить', 'ur-PK': 'ریفریش', 'tr-TR': 'Yenile' },
  post_loading_posts: { 'en-US': 'Loading social posts...', 'bn-BD': 'সোশ্যাল পোস্ট লোড হচ্ছে...', 'hi-IN': 'सोशल पोस्ट लोड हो रहे हैं...', 'ar-SA': 'جارٍ تحميل منشورات وسائل التواصل الاجتماعي...', 'es-ES': 'Cargando publicaciones sociales...', 'fr-FR': 'Chargement des publications sociales...', 'pt-BR': 'Carregando publicações sociais...', 'ru-RU': 'Загрузка социальных публикаций...', 'ur-PK': 'سوشل پوسٹس لوڈ ہو رہی ہیں...', 'tr-TR': 'Sosyal gönderiler yükleniyor...' },
  post_no_posts: { 'en-US': 'No social posts yet.', 'bn-BD': 'এখনো কোনো সোশ্যাল পোস্ট নেই।', 'hi-IN': 'अभी कोई सोशल पोस्ट नहीं।', 'ar-SA': 'لا توجد منشورات اجتماعية بعد.', 'es-ES': 'Aún no hay publicaciones sociales.', 'fr-FR': 'Aucune publication sociale pour l\'instant.', 'pt-BR': 'Ainda não há publicações sociais.', 'ru-RU': 'Социальных публикаций пока нет.', 'ur-PK': 'ابھی کوئی سوشل پوسٹ نہیں۔', 'tr-TR': 'Henüz sosyal gönderi yok.' },
  post_scheduled_for: { 'en-US': 'Scheduled for', 'bn-BD': 'সময়সূচী', 'hi-IN': 'शेड्यूल', 'ar-SA': 'مجدول ليوم', 'es-ES': 'Programado para', 'fr-FR': 'Programmé pour', 'pt-BR': 'Agendado para', 'ru-RU': 'Запланировано на', 'ur-PK': 'شیڈول', 'tr-TR': 'Zamanlandı' },
  post_created: { 'en-US': 'Created', 'bn-BD': 'তৈরি হয়েছে', 'hi-IN': 'बनाया गया', 'ar-SA': 'تم الإنشاء', 'es-ES': 'Creado', 'fr-FR': 'Créé', 'pt-BR': 'Criado', 'ru-RU': 'Создано', 'ur-PK': 'بنایا گیا', 'tr-TR': 'Oluşturuldu' },
  post_provider_id: { 'en-US': 'Provider ID', 'bn-BD': 'প্রদানকারী আইডি', 'hi-IN': 'प्रदाता आईडी', 'ar-SA': 'معرّف المزود', 'es-ES': 'ID del Proveedor', 'fr-FR': 'ID du Fournisseur', 'pt-BR': 'ID do Provedor', 'ru-RU': 'ID поставщика', 'ur-PK': 'فراہم کنندہ آئی ڈی', 'tr-TR': 'Sağlayıcı Kimliği' },
  post_err_no_prompt: { 'en-US': 'Enter a prompt to generate your post.', 'bn-BD': 'পোস্ট তৈরি করতে প্রম্পট লিখুন।', 'hi-IN': 'पोस्ट जनरेट करने के लिए प्रॉम्प्ट दर्ज करें।', 'ar-SA': 'أدخل أمراً لإنشاء منشورك.', 'es-ES': 'Ingresa una indicación para generar tu publicación.', 'fr-FR': 'Entrez une invite pour générer votre publication.', 'pt-BR': 'Digite um prompt para gerar sua publicação.', 'ru-RU': 'Введите запрос для создания публикации.', 'ur-PK': 'پوسٹ بنانے کے لیے پرامپٹ درج کریں۔', 'tr-TR': 'Gönderi oluşturmak için bir istem girin.' },
  post_err_write_first: { 'en-US': 'Write or generate content before publishing.', 'bn-BD': 'প্রকাশ করার আগে সামগ্রী লিখুন বা তৈরি করুন।', 'hi-IN': 'प्रकाशित करने से पहले सामग्री लिखें या जनरेट करें।', 'ar-SA': 'اكتب المحتوى أو أنشئه قبل النشر.', 'es-ES': 'Escribe o genera contenido antes de publicar.', 'fr-FR': 'Rédigez ou générez du contenu avant de publier.', 'pt-BR': 'Escreva ou gere conteúdo antes de publicar.', 'ru-RU': 'Напишите или создайте контент перед публикацией.', 'ur-PK': 'شائع کرنے سے پہلے مواد لکھیں یا بنائیں۔', 'tr-TR': 'Yayınlamadan önce içerik yazın veya oluşturun.' },
  post_err_connect_first: { 'en-US': 'Connect a supported social account before creating a post.', 'bn-BD': 'পোস্ট তৈরি করার আগে একটি সমর্থিত সোশ্যাল অ্যাকাউন্ট সংযুক্ত করুন।', 'hi-IN': 'पोस्ट बनाने से पहले एक समर्थित सोशल खाता कनेक्ट करें।', 'ar-SA': 'قم بتوصيل حساب اجتماعي مدعوم قبل إنشاء منشور.', 'es-ES': 'Conecta una cuenta social compatible antes de crear una publicación.', 'fr-FR': 'Connectez un compte social pris en charge avant de créer une publication.', 'pt-BR': 'Conecte uma conta social suportada antes de criar uma publicação.', 'ru-RU': 'Подключите поддерживаемый социальный аккаунт перед созданием публикации.', 'ur-PK': 'پوسٹ بنانے سے پہلے ایک معاون سوشل اکاؤنٹ جوڑیں۔', 'tr-TR': 'Gönderi oluşturmadan önce desteklenen bir sosyal hesap bağlayın.' },
  post_err_select_platform: { 'en-US': 'Select at least one connected platform.', 'bn-BD': 'কমপক্ষে একটি সংযুক্ত প্ল্যাটফর্ম নির্বাচন করুন।', 'hi-IN': 'कम से कम एक जुड़ा प्लेटफ़ॉर्म चुनें।', 'ar-SA': 'حدد منصة متصلة واحدة على الأقل.', 'es-ES': 'Selecciona al menos una plataforma conectada.', 'fr-FR': 'Sélectionnez au moins une plateforme connectée.', 'pt-BR': 'Selecione pelo menos uma plataforma conectada.', 'ru-RU': 'Выберите хотя бы одну подключённую платформу.', 'ur-PK': 'کم از کم ایک جڑا ہوا پلیٹ فارم منتخب کریں۔', 'tr-TR': 'En az bir bağlı platform seçin.' },
  post_err_choose_date: { 'en-US': 'Choose a schedule date first.', 'bn-BD': 'প্রথমে একটি সময়সূচী তারিখ বেছে নিন।', 'hi-IN': 'पहले शेड्यूल तारीख चुनें।', 'ar-SA': 'اختر تاريخ الجدولة أولاً.', 'es-ES': 'Elige primero una fecha de programación.', 'fr-FR': 'Choisissez d\'abord une date de programmation.', 'pt-BR': 'Escolha primeiro uma data de agendamento.', 'ru-RU': 'Сначала выберите дату публикации.', 'ur-PK': 'پہلے شیڈول تاریخ منتخب کریں۔', 'tr-TR': 'Önce bir zamanlama tarihi seçin.' },

  // Onboarding.jsx
  onb_step_role: { 'en-US': 'Your Role', 'bn-BD': 'আপনার ভূমিকা', 'hi-IN': 'आपकी भूमिका', 'ar-SA': 'دورك', 'es-ES': 'Tu Rol', 'fr-FR': 'Votre Rôle', 'pt-BR': 'Seu Papel', 'ru-RU': 'Ваша роль', 'ur-PK': 'آپ کا کردار', 'tr-TR': 'Rolünüz' },
  onb_step_goals: { 'en-US': 'Main Goals', 'bn-BD': 'প্রধান লক্ষ্য', 'hi-IN': 'मुख्य लक्ष्य', 'ar-SA': 'الأهداف الرئيسية', 'es-ES': 'Objetivos Principales', 'fr-FR': 'Objectifs Principaux', 'pt-BR': 'Objetivos Principais', 'ru-RU': 'Основные цели', 'ur-PK': 'بنیادی اہداف', 'tr-TR': 'Ana Hedefler' },
  onb_step_setup: { 'en-US': 'Profile Setup', 'bn-BD': 'প্রোফাইল সেটআপ', 'hi-IN': 'प्रोफ़ाइल सेटअप', 'ar-SA': 'إعداد الملف الشخصي', 'es-ES': 'Configuración de Perfil', 'fr-FR': 'Configuration du Profil', 'pt-BR': 'Configuração do Perfil', 'ru-RU': 'Настройка профиля', 'ur-PK': 'پروفائل سیٹ اپ', 'tr-TR': 'Profil Kurulumu' },
  onb_welcome_title: { 'en-US': 'Welcome! How do you identify?', 'bn-BD': 'স্বাগতম! আপনি কীভাবে নিজেকে পরিচয় দেন?', 'hi-IN': 'स्वागत है! आप खुद को कैसे पहचानते हैं?', 'ar-SA': 'مرحباً! كيف تعرّف نفسك؟', 'es-ES': '¡Bienvenido! ¿Cómo te identificas?', 'fr-FR': 'Bienvenue ! Comment vous identifiez-vous ?', 'pt-BR': 'Bem-vindo! Como você se identifica?', 'ru-RU': 'Добро пожаловать! Кем вы себя считаете?', 'ur-PK': 'خوش آمدید! آپ خود کو کیسے پہچانتے ہیں؟', 'tr-TR': 'Hoş Geldiniz! Kendinizi nasıl tanımlarsınız?' },
  onb_welcome_sub: { 'en-US': 'Select the role that best describes you to personalize your experience.', 'bn-BD': 'আপনার অভিজ্ঞতা ব্যক্তিগতকৃত করতে আপনাকে সবচেয়ে ভালো বর্ণনা করে এমন ভূমিকা নির্বাচন করুন।', 'hi-IN': 'अपने अनुभव को व्यक्तिगत बनाने के लिए वह भूमिका चुनें जो आपको सबसे अच्छी तरह बताती है।', 'ar-SA': 'حدد الدور الذي يصفك بشكل أفضل لتخصيص تجربتك.', 'es-ES': 'Selecciona el rol que mejor te describe para personalizar tu experiencia.', 'fr-FR': 'Sélectionnez le rôle qui vous décrit le mieux pour personnaliser votre expérience.', 'pt-BR': 'Selecione o papel que melhor te descreve para personalizar sua experiência.', 'ru-RU': 'Выберите роль, которая лучше всего вас описывает, для персонализации.', 'ur-PK': 'اپنے تجربے کو ذاتی بنانے کے لیے وہ کردار منتخب کریں جو آپ کو بہترین بیان کرے۔', 'tr-TR': 'Deneyiminizi kişiselleştirmek için sizi en iyi tanımlayan rolü seçin.' },
  onb_goals_title: { 'en-US': 'What are your main goals?', 'bn-BD': 'আপনার প্রধান লক্ষ্য কী?', 'hi-IN': 'आपके मुख्य लक्ष्य क्या हैं?', 'ar-SA': 'ما هي أهدافك الرئيسية؟', 'es-ES': '¿Cuáles son tus objetivos principales?', 'fr-FR': 'Quels sont vos objectifs principaux ?', 'pt-BR': 'Quais são seus objetivos principais?', 'ru-RU': 'Каковы ваши основные цели?', 'ur-PK': 'آپ کے بنیادی اہداف کیا ہیں؟', 'tr-TR': 'Ana hedefleriniz nelerdir?' },
  onb_goals_sub: { 'en-US': 'Select all that apply. We\'ll tailor your dashboard based on this.', 'bn-BD': 'প্রযোজ্য সব নির্বাচন করুন। আমরা এর ভিত্তিতে আপনার ড্যাশবোর্ড কাস্টমাইজ করব।', 'hi-IN': 'सभी लागू को चुनें। हम इसके आधार पर आपके डैशबोर्ड को अनुकूलित करेंगे।', 'ar-SA': 'حدد كل ما ينطبق. سنعدّل لوحة التحكم الخاصة بك بناءً على ذلك.', 'es-ES': 'Selecciona todos los que apliquen. Personalizaremos tu panel según esto.', 'fr-FR': 'Sélectionnez tout ce qui s\'applique. Nous adapterons votre tableau de bord en conséquence.', 'pt-BR': 'Selecione tudo que se aplica. Ajustaremos seu painel com base nisso.', 'ru-RU': 'Выберите всё, что применимо. Мы настроим ваш дашборд соответственно.', 'ur-PK': 'جو لاگو ہو وہ سب منتخب کریں۔ ہم اس کی بنیاد پر آپ کا ڈیش بورڈ موزوں بنائیں گے۔', 'tr-TR': 'Geçerli olanların hepsini seçin. Buna göre panonuzu özelleştireceğiz.' },
  onb_setup_title: { 'en-US': 'Just a few more details', 'bn-BD': 'আরও কয়েকটি বিবরণ', 'hi-IN': 'बस कुछ और विवरण', 'ar-SA': 'بعض التفاصيل الإضافية', 'es-ES': 'Solo algunos detalles más', 'fr-FR': 'Juste quelques détails supplémentaires', 'pt-BR': 'Apenas mais alguns detalhes', 'ru-RU': 'Ещё несколько деталей', 'ur-PK': 'بس چند اور تفصیلات', 'tr-TR': 'Birkaç ayrıntı daha' },
  onb_setup_sub: { 'en-US': 'Help us complete your professional profile.', 'bn-BD': 'আপনার পেশাদার প্রোফাইল সম্পূর্ণ করতে আমাদের সাহায্য করুন।', 'hi-IN': 'अपनी पेशेवर प्रोफ़ाइल पूरी करने में हमारी मदद करें।', 'ar-SA': 'ساعدنا في إكمال ملفك الشخصي المهني.', 'es-ES': 'Ayúdanos a completar tu perfil profesional.', 'fr-FR': 'Aidez-nous à compléter votre profil professionnel.', 'pt-BR': 'Ajude-nos a completar seu perfil profissional.', 'ru-RU': 'Помогите нам заполнить ваш профессиональный профиль.', 'ur-PK': 'اپنا پیشہ ورانہ پروفائل مکمل کرنے میں ہماری مدد کریں۔', 'tr-TR': 'Profesyonel profilinizi tamamlamamıza yardımcı olun.' },
  onb_lbl_company: { 'en-US': 'Company Name (Optional)', 'bn-BD': 'কোম্পানির নাম (ঐচ্ছিক)', 'hi-IN': 'कंपनी का नाम (वैकल्पिक)', 'ar-SA': 'اسم الشركة (اختياري)', 'es-ES': 'Nombre de la Empresa (Opcional)', 'fr-FR': 'Nom de l\'Entreprise (Optionnel)', 'pt-BR': 'Nome da Empresa (Opcional)', 'ru-RU': 'Название компании (необязательно)', 'ur-PK': 'کمپنی کا نام (اختیاری)', 'tr-TR': 'Şirket Adı (İsteğe Bağlı)' },
  onb_ph_company: { 'en-US': 'e.g. Acme Real Estate', 'bn-BD': 'যেমন: Acme Real Estate', 'hi-IN': 'जैसे: Acme Real Estate', 'ar-SA': 'مثال: Acme Real Estate', 'es-ES': 'ej. Acme Real Estate', 'fr-FR': 'ex. Acme Real Estate', 'pt-BR': 'ex. Acme Real Estate', 'ru-RU': 'напр. Acme Real Estate', 'ur-PK': 'مثلاً: Acme Real Estate', 'tr-TR': 'örn. Acme Real Estate' },
  onb_lbl_experience: { 'en-US': 'Years of Experience', 'bn-BD': 'অভিজ্ঞতার বছর', 'hi-IN': 'अनुभव के साल', 'ar-SA': 'سنوات الخبرة', 'es-ES': 'Años de Experiencia', 'fr-FR': 'Années d\'Expérience', 'pt-BR': 'Anos de Experiência', 'ru-RU': 'Лет опыта', 'ur-PK': 'تجربے کے سال', 'tr-TR': 'Deneyim Yılları' },
  onb_btn_back: { 'en-US': 'Back', 'bn-BD': 'পেছনে', 'hi-IN': 'वापस', 'ar-SA': 'رجوع', 'es-ES': 'Atrás', 'fr-FR': 'Retour', 'pt-BR': 'Voltar', 'ru-RU': 'Назад', 'ur-PK': 'واپس', 'tr-TR': 'Geri' },
  onb_btn_finishing: { 'en-US': 'Finishing...', 'bn-BD': 'সম্পন্ন হচ্ছে...', 'hi-IN': 'समाप्त हो रहा है...', 'ar-SA': 'جارٍ الإنهاء...', 'es-ES': 'Finalizando...', 'fr-FR': 'Finalisation...', 'pt-BR': 'Finalizando...', 'ru-RU': 'Завершение...', 'ur-PK': 'مکمل ہو رہا ہے...', 'tr-TR': 'Tamamlanıyor...' },
  onb_btn_dashboard: { 'en-US': 'Go to Dashboard', 'bn-BD': 'ড্যাশবোর্ডে যান', 'hi-IN': 'डैशबोर्ड पर जाएं', 'ar-SA': 'الذهاب إلى لوحة التحكم', 'es-ES': 'Ir al Panel', 'fr-FR': 'Aller au Tableau de Bord', 'pt-BR': 'Ir para o Painel', 'ru-RU': 'Перейти к дашборду', 'ur-PK': 'ڈیش بورڈ پر جائیں', 'tr-TR': 'Panele Git' },
  onb_btn_continue: { 'en-US': 'Continue', 'bn-BD': 'চালিয়ে যান', 'hi-IN': 'जारी रखें', 'ar-SA': 'متابعة', 'es-ES': 'Continuar', 'fr-FR': 'Continuer', 'pt-BR': 'Continuar', 'ru-RU': 'Продолжить', 'ur-PK': 'جاری رکھیں', 'tr-TR': 'Devam Et' },

  // JoinEvent.jsx
  event_title: { 'en-US': 'Discover & Join Events', 'bn-BD': 'ইভেন্ট আবিষ্কার করুন ও যোগ দিন', 'hi-IN': 'इवेंट खोजें और जुड़ें', 'ar-SA': 'اكتشف الأحداث وانضم إليها', 'es-ES': 'Descubrir y Unirse a Eventos', 'fr-FR': 'Découvrir et Rejoindre des Événements', 'pt-BR': 'Descobrir e Participar de Eventos', 'ru-RU': 'Находите события и вступайте в них', 'ur-PK': 'ایونٹس دریافت کریں اور شامل ہوں', 'tr-TR': 'Etkinlikleri Keşfet ve Katıl' },
  event_subtitle: { 'en-US': 'Browse live community events, filter them from the backend, and create new ones without leaving this screen.', 'bn-BD': 'লাইভ কমিউনিটি ইভেন্ট ব্রাউজ করুন, ফিল্টার করুন এবং এই স্ক্রিন না ছেড়ে নতুন তৈরি করুন।', 'hi-IN': 'लाइव कम्युनिटी इवेंट ब्राउज़ करें, फ़िल्टर करें और इस स्क्रीन को छोड़े बिना नए बनाएं।', 'ar-SA': 'تصفح أحداث المجتمع المباشرة وفلترها وأنشئ أحداثاً جديدة دون مغادرة هذه الشاشة.', 'es-ES': 'Explora eventos comunitarios en vivo, filtralos y crea nuevos sin salir de esta pantalla.', 'fr-FR': 'Parcourez les événements communautaires en direct, filtrez-les et créez-en de nouveaux sans quitter cet écran.', 'pt-BR': 'Navegue por eventos comunitários ao vivo, filtre-os e crie novos sem sair desta tela.', 'ru-RU': 'Просматривайте живые события сообщества, фильтруйте и создавайте новые, не покидая экран.', 'ur-PK': 'لائیو کمیونٹی ایونٹس براؤز کریں، فلٹر کریں اور اس اسکرین کو چھوڑے بغیر نئے بنائیں۔', 'tr-TR': 'Canlı topluluk etkinliklerine göz atın, filtreleyin ve bu ekranı terk etmeden yenilerini oluşturun.' },
  event_ph_search: { 'en-US': 'Search title, description, organizer, or location...', 'bn-BD': 'শিরোনাম, বিবরণ, আয়োজক বা অবস্থান খুঁজুন...', 'hi-IN': 'शीर्षक, विवरण, आयोजक या स्थान खोजें...', 'ar-SA': 'ابحث عن العنوان أو الوصف أو المنظم أو الموقع...', 'es-ES': 'Buscar título, descripción, organizador o ubicación...', 'fr-FR': 'Rechercher titre, description, organisateur ou lieu...', 'pt-BR': 'Pesquisar título, descrição, organizador ou local...', 'ru-RU': 'Поиск по названию, описанию, организатору или месту...', 'ur-PK': 'عنوان، تفصیل، منتظم یا مقام تلاش کریں...', 'tr-TR': 'Başlık, açıklama, organizatör veya konum ara...' },
  event_btn_search: { 'en-US': 'Search', 'bn-BD': 'খুঁজুন', 'hi-IN': 'खोजें', 'ar-SA': 'بحث', 'es-ES': 'Buscar', 'fr-FR': 'Rechercher', 'pt-BR': 'Pesquisar', 'ru-RU': 'Поиск', 'ur-PK': 'تلاش', 'tr-TR': 'Ara' },
  event_feed_title: { 'en-US': 'Community Event Feed', 'bn-BD': 'কমিউনিটি ইভেন্ট ফিড', 'hi-IN': 'कम्युनिटी इवेंट फ़ीड', 'ar-SA': 'خلاصة أحداث المجتمع', 'es-ES': 'Feed de Eventos de la Comunidad', 'fr-FR': 'Fil d\'Événements Communautaires', 'pt-BR': 'Feed de Eventos da Comunidade', 'ru-RU': 'Лента событий сообщества', 'ur-PK': 'کمیونٹی ایونٹ فیڈ', 'tr-TR': 'Topluluk Etkinlik Akışı' },
  event_all_cats: { 'en-US': 'All Categories', 'bn-BD': 'সকল বিভাগ', 'hi-IN': 'सभी श्रेणियाँ', 'ar-SA': 'جميع الفئات', 'es-ES': 'Todas las Categorías', 'fr-FR': 'Toutes les Catégories', 'pt-BR': 'Todas as Categorias', 'ru-RU': 'Все категории', 'ur-PK': 'تمام زمرے', 'tr-TR': 'Tüm Kategoriler' },
  event_lbl_events_count: { 'en-US': '{count} events', 'bn-BD': '{count} ইভেন্ট', 'hi-IN': '{count} इवेंट', 'ar-SA': '{count} أحداث', 'es-ES': '{count} eventos', 'fr-FR': '{count} événements', 'pt-BR': '{count} eventos', 'ru-RU': '{count} событий', 'ur-PK': '{count} ایونٹس', 'tr-TR': '{count} etkinlik' },
  event_loading: { 'en-US': 'Loading events...', 'bn-BD': 'ইভেন্ট লোড হচ্ছে...', 'hi-IN': 'इवेंट लोड हो रहे हैं...', 'ar-SA': 'جارٍ تحميل الأحداث...', 'es-ES': 'Cargando eventos...', 'fr-FR': 'Chargement des événements...', 'pt-BR': 'Carregando eventos...', 'ru-RU': 'Загрузка событий...', 'ur-PK': 'ایونٹس لوڈ ہو رہے ہیں...', 'tr-TR': 'Etkinlikler yükleniyor...' },
  event_empty: { 'en-US': 'No events found for this search and category.', 'bn-BD': 'এই অনুসন্ধান এবং বিভাগের জন্য কোনো ইভেন্ট পাওয়া যায়নি।', 'hi-IN': 'इस खोज और श्रेणी के लिए कोई इवेंट नहीं मिला।', 'ar-SA': 'لم يتم العثور على أحداث لهذا البحث والفئة.', 'es-ES': 'No se encontraron eventos para esta búsqueda y categoría.', 'fr-FR': 'Aucun événement trouvé pour cette recherche et cette catégorie.', 'pt-BR': 'Nenhum evento encontrado para esta pesquisa e categoria.', 'ru-RU': 'События не найдены для данного поиска и категории.', 'ur-PK': 'اس تلاش اور زمرے کے لیے کوئی ایونٹ نہیں ملا۔', 'tr-TR': 'Bu arama ve kategori için etkinlik bulunamadı.' },
  event_no_desc: { 'en-US': 'No description provided.', 'bn-BD': 'কোনো বিবরণ দেওয়া হয়নি।', 'hi-IN': 'कोई विवरण नहीं दिया गया।', 'ar-SA': 'لم يتم تقديم وصف.', 'es-ES': 'No se proporcionó descripción.', 'fr-FR': 'Aucune description fournie.', 'pt-BR': 'Nenhuma descrição fornecida.', 'ru-RU': 'Описание не предоставлено.', 'ur-PK': 'کوئی تفصیل فراہم نہیں کی گئی۔', 'tr-TR': 'Açıklama sağlanmadı.' },
  event_at_time: { 'en-US': 'at', 'bn-BD': 'এ', 'hi-IN': 'पर', 'ar-SA': 'في', 'es-ES': 'a las', 'fr-FR': 'à', 'pt-BR': 'às', 'ru-RU': 'в', 'ur-PK': 'پر', 'tr-TR': 'saat' },
  event_attending: { 'en-US': 'Attending', 'bn-BD': 'অংশগ্রহণকারী', 'hi-IN': 'उपस्थित', 'ar-SA': 'الحضور', 'es-ES': 'Asistentes', 'fr-FR': 'Participants', 'pt-BR': 'Presença', 'ru-RU': 'Участников', 'ur-PK': 'شرکت', 'tr-TR': 'Katılıyor' },
  event_hdr_create: { 'en-US': 'Create Event', 'bn-BD': 'ইভেন্ট তৈরি করুন', 'hi-IN': 'इवेंट बनाएं', 'ar-SA': 'إنشاء حدث', 'es-ES': 'Crear Evento', 'fr-FR': 'Créer un Événement', 'pt-BR': 'Criar Evento', 'ru-RU': 'Создать событие', 'ur-PK': 'ایونٹ بنائیں', 'tr-TR': 'Etkinlik Oluştur' },
  event_ph_ev_title: { 'en-US': 'Event title', 'bn-BD': 'ইভেন্টের শিরোনাম', 'hi-IN': 'इवेंट शीर्षक', 'ar-SA': 'عنوان الحدث', 'es-ES': 'Título del evento', 'fr-FR': 'Titre de l\'événement', 'pt-BR': 'Título do evento', 'ru-RU': 'Название события', 'ur-PK': 'ایونٹ عنوان', 'tr-TR': 'Etkinlik başlığı' },
  event_ph_capacity: { 'en-US': 'Capacity', 'bn-BD': 'ধারণক্ষমতা', 'hi-IN': 'क्षमता', 'ar-SA': 'السعة', 'es-ES': 'Capacidad', 'fr-FR': 'Capacité', 'pt-BR': 'Capacidade', 'ru-RU': 'Вместимость', 'ur-PK': 'گنجائش', 'tr-TR': 'Kapasite' },
  event_ph_description: { 'en-US': 'Description', 'bn-BD': 'বিবরণ', 'hi-IN': 'विवरण', 'ar-SA': 'الوصف', 'es-ES': 'Descripción', 'fr-FR': 'Description', 'pt-BR': 'Descrição', 'ru-RU': 'Описание', 'ur-PK': 'تفصیل', 'tr-TR': 'Açıklama' },
  event_ph_location: { 'en-US': 'Location', 'bn-BD': 'অবস্থান', 'hi-IN': 'स्थान', 'ar-SA': 'الموقع', 'es-ES': 'Ubicación', 'fr-FR': 'Lieu', 'pt-BR': 'Local', 'ru-RU': 'Место', 'ur-PK': 'مقام', 'tr-TR': 'Konum' },
  event_ph_link: { 'en-US': 'Online meeting link', 'bn-BD': 'অনলাইন মিটিং লিংক', 'hi-IN': 'ऑनलाइन मीटिंग लिंक', 'ar-SA': 'رابط الاجتماع الإلكتروني', 'es-ES': 'Enlace de reunión en línea', 'fr-FR': 'Lien de réunion en ligne', 'pt-BR': 'Link da reunião online', 'ru-RU': 'Ссылка на онлайн-встречу', 'ur-PK': 'آن لائن میٹنگ لنک', 'tr-TR': 'Çevrimiçi toplantı bağlantısı' },
  event_ph_start_time: { 'en-US': 'Start time (e.g. 18:30)', 'bn-BD': 'শুরুর সময় (যেমন: ১৮:৩০)', 'hi-IN': 'शुरू का समय (जैसे 18:30)', 'ar-SA': 'وقت البدء (مثل 18:30)', 'es-ES': 'Hora de inicio (ej. 18:30)', 'fr-FR': 'Heure de début (ex. 18h30)', 'pt-BR': 'Hora de início (ex. 18:30)', 'ru-RU': 'Время начала (напр. 18:30)', 'ur-PK': 'شروع کا وقت (مثلاً 18:30)', 'tr-TR': 'Başlangıç saati (örn. 18:30)' },
  event_ph_end_time: { 'en-US': 'End time', 'bn-BD': 'শেষ সময়', 'hi-IN': 'समाप्ति समय', 'ar-SA': 'وقت الانتهاء', 'es-ES': 'Hora de fin', 'fr-FR': 'Heure de fin', 'pt-BR': 'Hora de fim', 'ru-RU': 'Время окончания', 'ur-PK': 'ختم کا وقت', 'tr-TR': 'Bitiş saati' },
  event_ph_timezone: { 'en-US': 'Timezone', 'bn-BD': 'সময় অঞ্চল', 'hi-IN': 'टाइमज़ोन', 'ar-SA': 'المنطقة الزمنية', 'es-ES': 'Zona horaria', 'fr-FR': 'Fuseau horaire', 'pt-BR': 'Fuso horário', 'ru-RU': 'Часовой пояс', 'ur-PK': 'ٹائم زون', 'tr-TR': 'Saat dilimi' },
  event_btn_create: { 'en-US': 'Create Event', 'bn-BD': 'ইভেন্ট তৈরি করুন', 'hi-IN': 'इवेंट बनाएं', 'ar-SA': 'إنشاء حدث', 'es-ES': 'Crear Evento', 'fr-FR': 'Créer l\'Événement', 'pt-BR': 'Criar Evento', 'ru-RU': 'Создать событие', 'ur-PK': 'ایونٹ بنائیں', 'tr-TR': 'Etkinlik Oluştur' },
  event_no_link: { 'en-US': 'No online link provided.', 'bn-BD': 'কোনো অনলাইন লিংক দেওয়া হয়নি।', 'hi-IN': 'कोई ऑनलाइन लिंक प्रदान नहीं किया गया।', 'ar-SA': 'لم يتم توفير رابط إلكتروني.', 'es-ES': 'No se proporcionó enlace en línea.', 'fr-FR': 'Aucun lien en ligne fourni.', 'pt-BR': 'Nenhum link online fornecido.', 'ru-RU': 'Онлайн-ссылка не предоставлена.', 'ur-PK': 'کوئی آن لائن لنک فراہم نہیں کیا گیا۔', 'tr-TR': 'Çevrimiçi bağlantı sağlanmadı.' },
  event_joined_count: { 'en-US': 'joined', 'bn-BD': 'যোগ দিয়েছেন', 'hi-IN': 'शामिल हुए', 'ar-SA': 'انضم', 'es-ES': 'inscritos', 'fr-FR': 'inscrits', 'pt-BR': 'inscritos', 'ru-RU': 'вступили', 'ur-PK': 'شامل', 'tr-TR': 'katıldı' },
  event_organized_by: { 'en-US': 'Organized by', 'bn-BD': 'আয়োজক', 'hi-IN': 'द्वारा आयोजित', 'ar-SA': 'منظَّم بواسطة', 'es-ES': 'Organizado por', 'fr-FR': 'Organisé par', 'pt-BR': 'Organizado por', 'ru-RU': 'Организовано', 'ur-PK': 'منتظم', 'tr-TR': 'Düzenleyen' },
  event_btn_leave: { 'en-US': 'Leave Event', 'bn-BD': 'ইভেন্ট ছেড়ে দিন', 'hi-IN': 'इवेंट छोड़ें', 'ar-SA': 'مغادرة الحدث', 'es-ES': 'Abandonar Evento', 'fr-FR': 'Quitter l\'Événement', 'pt-BR': 'Sair do Evento', 'ru-RU': 'Покинуть событие', 'ur-PK': 'ایونٹ چھوڑیں', 'tr-TR': 'Etkinlikten Ayrıl' },
  event_btn_join: { 'en-US': 'Join Event', 'bn-BD': 'ইভেন্টে যোগ দিন', 'hi-IN': 'इवेंट में शामिल हों', 'ar-SA': 'الانضمام إلى الحدث', 'es-ES': 'Unirse al Evento', 'fr-FR': 'Rejoindre l\'Événement', 'pt-BR': 'Participar do Evento', 'ru-RU': 'Вступить в событие', 'ur-PK': 'ایونٹ میں شامل ہوں', 'tr-TR': 'Etkinliğe Katıl' },
  event_none_selected: { 'en-US': 'No Event Selected', 'bn-BD': 'কোনো ইভেন্ট নির্বাচন করা হয়নি', 'hi-IN': 'कोई इवेंट नहीं चुना गया', 'ar-SA': 'لم يتم اختيار حدث', 'es-ES': 'Ningún Evento Seleccionado', 'fr-FR': 'Aucun Événement Sélectionné', 'pt-BR': 'Nenhum Evento Selecionado', 'ru-RU': 'Событие не выбрано', 'ur-PK': 'کوئی ایونٹ منتخب نہیں', 'tr-TR': 'Etkinlik Seçilmedi' },
  event_none_hint: { 'en-US': 'Choose an event from the list to inspect details or attendance.', 'bn-BD': 'বিবরণ বা উপস্থিতি দেখতে তালিকা থেকে একটি ইভেন্ট বেছে নিন।', 'hi-IN': 'विवरण या उपस्थिति देखने के लिए सूची से कोई इवेंट चुनें।', 'ar-SA': 'اختر حدثاً من القائمة لفحص التفاصيل أو الحضور.', 'es-ES': 'Elige un evento de la lista para ver detalles o asistencia.', 'fr-FR': 'Choisissez un événement dans la liste pour inspecter les détails ou la participation.', 'pt-BR': 'Escolha um evento da lista para ver detalhes ou presença.', 'ru-RU': 'Выберите событие из списка для просмотра деталей или посещаемости.', 'ur-PK': 'تفصیلات یا حاضری دیکھنے کے لیے فہرست سے ایونٹ منتخب کریں۔', 'tr-TR': 'Ayrıntıları veya katılımı incelemek için listeden bir etkinlik seçin.' },
  event_err_title_req: { 'en-US': 'Event title is required.', 'bn-BD': 'ইভেন্টের শিরোনাম প্রয়োজন।', 'hi-IN': 'इवेंट शीर्षक आवश्यक है।', 'ar-SA': 'عنوان الحدث مطلوب.', 'es-ES': 'El título del evento es obligatorio.', 'fr-FR': 'Le titre de l\'événement est obligatoire.', 'pt-BR': 'O título do evento é obrigatório.', 'ru-RU': 'Название события обязательно.', 'ur-PK': 'ایونٹ کا عنوان ضروری ہے۔', 'tr-TR': 'Etkinlik başlığı gereklidir.' },
  event_err_date_req: { 'en-US': 'Event date and start time are required.', 'bn-BD': 'ইভেন্টের তারিখ এবং শুরুর সময় প্রয়োজন।', 'hi-IN': 'इवेंट की तारीख और शुरू का समय आवश्यक है।', 'ar-SA': 'تاريخ الحدث ووقت البدء مطلوبان.', 'es-ES': 'La fecha del evento y la hora de inicio son obligatorias.', 'fr-FR': 'La date de l\'événement et l\'heure de début sont obligatoires.', 'pt-BR': 'A data do evento e a hora de início são obrigatórias.', 'ru-RU': 'Дата события и время начала обязательны.', 'ur-PK': 'ایونٹ کی تاریخ اور شروع کا وقت ضروری ہے۔', 'tr-TR': 'Etkinlik tarihi ve başlangıç saati gereklidir.' },
  event_success_created: { 'en-US': 'Event created successfully.', 'bn-BD': 'ইভেন্ট সফলভাবে তৈরি হয়েছে।', 'hi-IN': 'इवेंट सफलतापूर्वक बनाया गया।', 'ar-SA': 'تم إنشاء الحدث بنجاح.', 'es-ES': 'Evento creado con éxito.', 'fr-FR': 'Événement créé avec succès.', 'pt-BR': 'Evento criado com sucesso.', 'ru-RU': 'Событие успешно создано.', 'ur-PK': 'ایونٹ کامیابی سے بنایا گیا۔', 'tr-TR': 'Etkinlik başarıyla oluşturuldu.' },
  event_success_joined: { 'en-US': 'You joined the event.', 'bn-BD': 'আপনি ইভেন্টে যোগ দিয়েছেন।', 'hi-IN': 'आप इवेंट में शामिल हुए।', 'ar-SA': 'لقد انضممت إلى الحدث.', 'es-ES': 'Te has unido al evento.', 'fr-FR': 'Vous avez rejoint l\'événement.', 'pt-BR': 'Você participou do evento.', 'ru-RU': 'Вы вступили в событие.', 'ur-PK': 'آپ ایونٹ میں شامل ہو گئے۔', 'tr-TR': 'Etkinliğe katıldınız.' },
  event_success_left: { 'en-US': 'You left the event.', 'bn-BD': 'আপনি ইভেন্ট ছেড়েছেন।', 'hi-IN': 'आपने इवेंट छोड़ दिया।', 'ar-SA': 'لقد غادرت الحدث.', 'es-ES': 'Has abandonado el evento.', 'fr-FR': 'Vous avez quitté l\'événement.', 'pt-BR': 'Você saiu do evento.', 'ru-RU': 'Вы покинули событие.', 'ur-PK': 'آپ نے ایونٹ چھوڑ دیا۔', 'tr-TR': 'Etkinlikten ayrıldınız.' },

  // Shop.jsx
  shop_title: { 'en-US': 'Shop', 'bn-BD': 'শপ', 'hi-IN': 'शॉप', 'ar-SA': 'المتجر', 'es-ES': 'Tienda', 'fr-FR': 'Boutique', 'pt-BR': 'Loja', 'ru-RU': 'Магазин', 'ur-PK': 'شاپ', 'tr-TR': 'Mağaza' },
  shop_subtitle: { 'en-US': 'Browse and purchase official Mabdel fitness products, gear, and nutrition.', 'bn-BD': 'অফিসিয়াল Mabdel ফিটনেস পণ্য, সরঞ্জাম এবং পুষ্টি ব্রাউজ করুন ও কিনুন।', 'hi-IN': 'Mabdel के आधिकारिक फिटनेस उत्पाद, गियर और पोषण ब्राउज़ करें और खरीदें।', 'ar-SA': 'تصفح منتجات Mabdel الرسمية للياقة البدنية والمعدات والتغذية واشترها.', 'es-ES': 'Navega y compra los productos oficiales de fitness, equipos y nutrición de Mabdel.', 'fr-FR': 'Parcourez et achetez les produits de fitness, équipements et nutrition officiels Mabdel.', 'pt-BR': 'Navegue e compre produtos oficiais de fitness, equipamentos e nutrição Mabdel.', 'ru-RU': 'Просматривайте и покупайте официальные фитнес-продукты, снаряжение и питание Mabdel.', 'ur-PK': 'Mabdel کی آفیشل فٹنس مصنوعات، گیئر اور نیوٹریشن براؤز اور خریدیں۔', 'tr-TR': 'Mabdel\'in resmi fitness ürünlerini, ekipmanlarını ve beslenme ürünlerini keşfedin ve satın alın.' },
  shop_ph_search: { 'en-US': 'Search products...', 'bn-BD': 'পণ্য খুঁজুন...', 'hi-IN': 'उत्पाद खोजें...', 'ar-SA': 'ابحث عن المنتجات...', 'es-ES': 'Buscar productos...', 'fr-FR': 'Rechercher des produits...', 'pt-BR': 'Pesquisar produtos...', 'ru-RU': 'Поиск товаров...', 'ur-PK': 'مصنوعات تلاش کریں...', 'tr-TR': 'Ürün ara...' },
  shop_empty_title: { 'en-US': 'No Products Found', 'bn-BD': 'কোনো পণ্য পাওয়া যায়নি', 'hi-IN': 'कोई उत्पाद नहीं मिला', 'ar-SA': 'لم يتم العثور على منتجات', 'es-ES': 'No se Encontraron Productos', 'fr-FR': 'Aucun Produit Trouvé', 'pt-BR': 'Nenhum Produto Encontrado', 'ru-RU': 'Товары не найдены', 'ur-PK': 'کوئی مصنوعہ نہیں ملا', 'tr-TR': 'Ürün Bulunamadı' },
  shop_empty_hint: { 'en-US': 'Try adjusting your filters or search query.', 'bn-BD': 'ফিল্টার বা অনুসন্ধান পরিবর্তন করুন।', 'hi-IN': 'अपने फ़िल्टर या खोज क्वेरी को समायोजित करें।', 'ar-SA': 'حاول ضبط الفلاتر أو استعلام البحث.', 'es-ES': 'Intenta ajustar tus filtros o consulta de búsqueda.', 'fr-FR': 'Essayez d\'ajuster vos filtres ou votre requête de recherche.', 'pt-BR': 'Tente ajustar seus filtros ou consulta de pesquisa.', 'ru-RU': 'Попробуйте изменить фильтры или поисковый запрос.', 'ur-PK': 'فلٹرز یا تلاش درست کریں۔', 'tr-TR': 'Filtrelerinizi veya arama sorgunuzu ayarlamayı deneyin.' },
  shop_btn_details: { 'en-US': 'Details', 'bn-BD': 'বিবরণ', 'hi-IN': 'विवरण', 'ar-SA': 'التفاصيل', 'es-ES': 'Detalles', 'fr-FR': 'Détails', 'pt-BR': 'Detalhes', 'ru-RU': 'Подробнее', 'ur-PK': 'تفصیلات', 'tr-TR': 'Ayrıntılar' },
  shop_btn_buy: { 'en-US': 'Buy Now', 'bn-BD': 'এখনই কিনুন', 'hi-IN': 'अभी खरीदें', 'ar-SA': 'اشتر الآن', 'es-ES': 'Comprar Ahora', 'fr-FR': 'Acheter Maintenant', 'pt-BR': 'Comprar Agora', 'ru-RU': 'Купить сейчас', 'ur-PK': 'ابھی خریدیں', 'tr-TR': 'Şimdi Satın Al' },
  shop_lbl_availability: { 'en-US': 'Availability', 'bn-BD': 'উপলব্ধতা', 'hi-IN': 'उपलब्धता', 'ar-SA': 'التوفر', 'es-ES': 'Disponibilidad', 'fr-FR': 'Disponibilité', 'pt-BR': 'Disponibilidade', 'ru-RU': 'Наличие', 'ur-PK': 'دستیابی', 'tr-TR': 'Stok Durumu' },
  shop_in_stock: { 'en-US': 'In Stock ({count} left)', 'bn-BD': 'স্টকে আছে ({count} বাকি)', 'hi-IN': 'स्टॉक में ({count} बचा)', 'ar-SA': 'متوفر ({count} متبقية)', 'es-ES': 'En Stock ({count} restantes)', 'fr-FR': 'En Stock ({count} restants)', 'pt-BR': 'Em Estoque ({count} restantes)', 'ru-RU': 'В наличии (осталось {count})', 'ur-PK': 'اسٹاک میں ({count} باقی)', 'tr-TR': 'Stokta ({count} kaldı)' },
  shop_lbl_delivery: { 'en-US': 'Delivery', 'bn-BD': 'ডেলিভারি', 'hi-IN': 'डिलीवरी', 'ar-SA': 'التوصيل', 'es-ES': 'Entrega', 'fr-FR': 'Livraison', 'pt-BR': 'Entrega', 'ru-RU': 'Доставка', 'ur-PK': 'ڈیلیوری', 'tr-TR': 'Teslimat' },
  shop_delivery_val: { 'en-US': 'Free Express (3-5 Days)', 'bn-BD': 'বিনামূল্যে এক্সপ্রেস (৩-৫ দিন)', 'hi-IN': 'मुफ़्त एक्सप्रेस (3-5 दिन)', 'ar-SA': 'شحن سريع مجاني (3-5 أيام)', 'es-ES': 'Exprés Gratis (3-5 Días)', 'fr-FR': 'Express Gratuit (3-5 Jours)', 'pt-BR': 'Expresso Grátis (3-5 Dias)', 'ru-RU': 'Бесплатная экспресс-доставка (3-5 дней)', 'ur-PK': 'مفت ایکسپریس (3-5 دن)', 'tr-TR': 'Ücretsiz Ekspres (3-5 Gün)' },
  shop_btn_close: { 'en-US': 'Close', 'bn-BD': 'বন্ধ করুন', 'hi-IN': 'बंद करें', 'ar-SA': 'إغلاق', 'es-ES': 'Cerrar', 'fr-FR': 'Fermer', 'pt-BR': 'Fechar', 'ru-RU': 'Закрыть', 'ur-PK': 'بند کریں', 'tr-TR': 'Kapat' },
  shop_checkout_title: { 'en-US': 'Payment Checkout', 'bn-BD': 'পেমেন্ট চেকআউট', 'hi-IN': 'भुगतान चेकआउट', 'ar-SA': 'الدفع', 'es-ES': 'Pago', 'fr-FR': 'Paiement', 'pt-BR': 'Pagamento', 'ru-RU': 'Оплата', 'ur-PK': 'ادائیگی', 'tr-TR': 'Ödeme' },
  shop_checkout_sub: { 'en-US': 'Enter your card details to complete your checkout purchase.', 'bn-BD': 'চেকআউট সম্পন্ন করতে আপনার কার্ডের তথ্য লিখুন।', 'hi-IN': 'चेकआउट पूरा करने के लिए अपना कार्ड विवरण दर्ज करें।', 'ar-SA': 'أدخل تفاصيل بطاقتك لإتمام عملية الدفع.', 'es-ES': 'Ingresa los detalles de tu tarjeta para completar tu compra.', 'fr-FR': 'Entrez les détails de votre carte pour finaliser votre achat.', 'pt-BR': 'Digite os detalhes do cartão para concluir sua compra.', 'ru-RU': 'Введите данные карты для завершения покупки.', 'ur-PK': 'خریداری مکمل کرنے کے لیے اپنے کارڈ کی تفصیلات درج کریں۔', 'tr-TR': 'Ödemeyi tamamlamak için kart bilgilerinizi girin.' },
  shop_qty: { 'en-US': 'Qty: 1', 'bn-BD': 'পরিমাণ: ১', 'hi-IN': 'मात्रा: 1', 'ar-SA': 'الكمية: 1', 'es-ES': 'Cant.: 1', 'fr-FR': 'Qté : 1', 'pt-BR': 'Qtd: 1', 'ru-RU': 'Кол-во: 1', 'ur-PK': 'تعداد: 1', 'tr-TR': 'Adet: 1' },
  shop_ph_cardholder: { 'en-US': 'Cardholder Name', 'bn-BD': 'কার্ডধারীর নাম', 'hi-IN': 'कार्डधारक का नाम', 'ar-SA': 'اسم حامل البطاقة', 'es-ES': 'Nombre del Titular', 'fr-FR': 'Nom du Titulaire', 'pt-BR': 'Nome do Titular', 'ru-RU': 'Имя держателя карты', 'ur-PK': 'کارڈ ہولڈر کا نام', 'tr-TR': 'Kart Sahibinin Adı' },
  shop_ph_card_number: { 'en-US': 'Card Number', 'bn-BD': 'কার্ড নম্বর', 'hi-IN': 'कार्ड नंबर', 'ar-SA': 'رقم البطاقة', 'es-ES': 'Número de Tarjeta', 'fr-FR': 'Numéro de Carte', 'pt-BR': 'Número do Cartão', 'ru-RU': 'Номер карты', 'ur-PK': 'کارڈ نمبر', 'tr-TR': 'Kart Numarası' },
  shop_security: { 'en-US': 'Secured Stripe Gateway Integration', 'bn-BD': 'সুরক্ষিত Stripe গেটওয়ে', 'hi-IN': 'सुरक्षित Stripe गेटवे इंटीग्रेशन', 'ar-SA': 'بوابة Stripe الآمنة', 'es-ES': 'Integración Segura de Stripe', 'fr-FR': 'Intégration Sécurisée Stripe', 'pt-BR': 'Integração Segura do Stripe', 'ru-RU': 'Защищённый платёжный шлюз Stripe', 'ur-PK': 'محفوظ Stripe گیٹ وے', 'tr-TR': 'Güvenli Stripe Ödeme Entegrasyonu' },
  shop_btn_confirm_pay: { 'en-US': 'Confirm & Pay', 'bn-BD': 'নিশ্চিত করুন ও পেমেন্ট করুন', 'hi-IN': 'पुष्टि करें और भुगतान करें', 'ar-SA': 'تأكيد والدفع', 'es-ES': 'Confirmar y Pagar', 'fr-FR': 'Confirmer et Payer', 'pt-BR': 'Confirmar e Pagar', 'ru-RU': 'Подтвердить и оплатить', 'ur-PK': 'تصدیق کریں اور ادا کریں', 'tr-TR': 'Onayla ve Öde' },
  shop_processing_title: { 'en-US': 'Processing Transaction...', 'bn-BD': 'লেনদেন প্রক্রিয়া করা হচ্ছে...', 'hi-IN': 'लेनदेन प्रक्रिया में...', 'ar-SA': 'جارٍ معالجة المعاملة...', 'es-ES': 'Procesando Transacción...', 'fr-FR': 'Traitement de la Transaction...', 'pt-BR': 'Processando Transação...', 'ru-RU': 'Обработка транзакции...', 'ur-PK': 'لین دین پروسیس ہو رہا ہے...', 'tr-TR': 'İşlem Gerçekleştiriliyor...' },
  shop_processing_sub: { 'en-US': 'Authenticating and verifying payment credentials with card issuer...', 'bn-BD': 'কার্ড ইস্যুয়ারের সাথে পেমেন্ট শংসাপত্র যাচাই করা হচ্ছে...', 'hi-IN': 'कार्ड जारीकर्ता के साथ भुगतान प्रमाण-पत्र प्रमाणित और सत्यापित किया जा रहा है...', 'ar-SA': 'جارٍ مصادقة بيانات الدفع والتحقق منها مع جهة إصدار البطاقة...', 'es-ES': 'Autenticando y verificando credenciales de pago con el emisor de la tarjeta...', 'fr-FR': 'Authentification et vérification des identifiants de paiement auprès de l\'émetteur de la carte...', 'pt-BR': 'Autenticando e verificando credenciais de pagamento com o emissor do cartão...', 'ru-RU': 'Аутентификация и проверка платёжных данных у эмитента карты...', 'ur-PK': 'کارڈ جاری کنندہ سے ادائیگی کی تصدیق ہو رہی ہے...', 'tr-TR': 'Kart vericisiyle ödeme kimlik bilgileri doğrulanıyor...' },
  shop_success_title: { 'en-US': 'Payment Successful', 'bn-BD': 'পেমেন্ট সফল', 'hi-IN': 'भुगतान सफल', 'ar-SA': 'تمت عملية الدفع بنجاح', 'es-ES': 'Pago Exitoso', 'fr-FR': 'Paiement Réussi', 'pt-BR': 'Pagamento Bem-sucedido', 'ru-RU': 'Оплата прошла успешно', 'ur-PK': 'ادائیگی کامیاب', 'tr-TR': 'Ödeme Başarılı' },
  shop_success_sub: { 'en-US': 'Your purchase of {name} has been confirmed. A receipt has been sent to your email.', 'bn-BD': '{name}-এর আপনার ক্রয় নিশ্চিত হয়েছে। একটি রসিদ আপনার ইমেইলে পাঠানো হয়েছে।', 'hi-IN': '{name} की आपकी खरीद की पुष्टि हो गई है। एक रसीद आपके ईमेल पर भेज दी गई है।', 'ar-SA': 'تم تأكيد شراءك لـ {name}. تم إرسال إيصال إلى بريدك الإلكتروني.', 'es-ES': 'Tu compra de {name} ha sido confirmada. Se ha enviado un recibo a tu correo electrónico.', 'fr-FR': 'Votre achat de {name} a été confirmé. Un reçu a été envoyé à votre adresse e-mail.', 'pt-BR': 'Sua compra de {name} foi confirmada. Um recibo foi enviado para seu e-mail.', 'ru-RU': 'Ваша покупка {name} подтверждена. Квитанция отправлена на вашу почту.', 'ur-PK': '{name} کی آپ کی خریداری کی تصدیق ہو گئی۔ رسید آپ کی ای میل پر بھیج دی گئی۔', 'tr-TR': '{name} alımınız onaylandı. E-postanıza bir makbuz gönderildi.' },
  shop_btn_done: { 'en-US': 'Done', 'bn-BD': 'সম্পন্ন', 'hi-IN': 'हो गया', 'ar-SA': 'تم', 'es-ES': 'Listo', 'fr-FR': 'Terminé', 'pt-BR': 'Concluído', 'ru-RU': 'Готово', 'ur-PK': 'ہو گیا', 'tr-TR': 'Tamam' },
  shop_err_card_details: { 'en-US': 'Please fill in all credit card details.', 'bn-BD': 'অনুগ্রহ করে সমস্ত ক্রেডিট কার্ডের বিবরণ পূরণ করুন।', 'hi-IN': 'कृपया सभी क्रेडिट कार्ड विवरण भरें।', 'ar-SA': 'يرجى ملء جميع تفاصيل بطاقة الائتمان.', 'es-ES': 'Por favor, completa todos los detalles de la tarjeta de crédito.', 'fr-FR': 'Veuillez remplir tous les détails de la carte de crédit.', 'pt-BR': 'Por favor, preencha todos os detalhes do cartão de crédito.', 'ru-RU': 'Пожалуйста, заполните все данные кредитной карты.', 'ur-PK': 'براہ کرم تمام کریڈٹ کارڈ کی تفصیلات پُر کریں۔', 'tr-TR': 'Lütfen tüm kredi kartı bilgilerini doldurun.' },
};

const filePath = 'c:/project/Mabdel AI/Mabdel Website/src/i18n/translations.js';
let content = fs.readFileSync(filePath, 'utf-8');

const langs = ['en-US', 'bn-BD', 'hi-IN', 'ar-SA', 'es-ES', 'fr-FR', 'pt-BR', 'ru-RU', 'ur-PK', 'tr-TR'];

for (const lang of langs) {
  const targetTag = `'${lang}': {`;
  const pos = content.indexOf(targetTag);
  if (pos === -1) {
    console.error(`Could not find block for ${lang}`);
    process.exit(1);
  }

  const keyLines = Object.entries(translations)
    .map(([k, vals]) => `    ${k}: ${JSON.stringify(vals[lang] || vals['en-US'])},`)
    .join('\n');

  const blockEndPos = content.indexOf('  },', pos);
  content = content.slice(0, blockEndPos) + keyLines + '\n' + content.slice(blockEndPos);
}

fs.writeFileSync(filePath, content, 'utf-8');
console.log(`Successfully appended keys to all ${langs.length} language blocks!`);
