import fs from 'fs';

// Keys missing from translations.js needed by CreatePost.jsx, Onboarding.jsx, Shop.jsx
const translations = {
  // CreatePost.jsx – error messages
  post_err_enter_prompt: { 'en-US': 'Enter a prompt to generate your post.', 'bn-BD': 'পোস্ট তৈরি করতে একটি প্রম্পট দিন।', 'hi-IN': 'पोस्ट जनरेट करने के लिए प्रॉम्प्ट दर्ज करें।', 'ar-SA': 'أدخل طلبًا لإنشاء منشورك.', 'es-ES': 'Introduce un prompt para generar tu publicación.', 'fr-FR': 'Entrez une invite pour générer votre publication.', 'pt-BR': 'Digite um prompt para gerar sua publicação.', 'ru-RU': 'Введите запрос для создания публикации.', 'ur-PK': 'پوسٹ بنانے کے لیے پرامپٹ درج کریں۔', 'tr-TR': 'Gönderi oluşturmak için bir istem girin.' },
  post_err_write_content: { 'en-US': 'Write or generate content before publishing.', 'bn-BD': 'প্রকাশের আগে কন্টেন্ট লিখুন বা তৈরি করুন।', 'hi-IN': 'प्रकाशित करने से पहले सामग्री लिखें या जनरेट करें।', 'ar-SA': 'اكتب أو أنشئ محتوى قبل النشر.', 'es-ES': 'Escribe o genera contenido antes de publicar.', 'fr-FR': 'Rédigez ou générez du contenu avant de publier.', 'pt-BR': 'Escreva ou gere conteúdo antes de publicar.', 'ru-RU': 'Напишите или создайте содержание перед публикацией.', 'ur-PK': 'شائع کرنے سے پہلے مواد لکھیں یا بنائیں۔', 'tr-TR': 'Yayınlamadan önce içerik yazın veya oluşturun.' },
  post_err_connect_account: { 'en-US': 'Connect a supported social account before creating a post.', 'bn-BD': 'পোস্ট তৈরির আগে একটি সমর্থিত সোশ্যাল অ্যাকাউন্ট সংযুক্ত করুন।', 'hi-IN': 'पोस्ट बनाने से पहले एक समर्थित सोशल अकाउंट कनेक्ट करें।', 'ar-SA': 'قم بتوصيل حساب اجتماعي مدعوم قبل إنشاء منشور.', 'es-ES': 'Conecta una cuenta social compatible antes de crear una publicación.', 'fr-FR': 'Connectez un compte social compatible avant de créer une publication.', 'pt-BR': 'Conecte uma conta social suportada antes de criar uma publicação.', 'ru-RU': 'Подключите поддерживаемый социальный аккаунт перед созданием публикации.', 'ur-PK': 'پوسٹ بنانے سے پہلے ایک معاون سوشل اکاؤنٹ جوڑیں۔', 'tr-TR': 'Gönderi oluşturmadan önce desteklenen bir sosyal hesap bağlayın.' },
  post_err_select_platform: { 'en-US': 'Select at least one connected platform.', 'bn-BD': 'কমপক্ষে একটি সংযুক্ত প্ল্যাটফর্ম নির্বাচন করুন।', 'hi-IN': 'कम से कम एक जुड़ा प्लेटफ़ॉर्म चुनें।', 'ar-SA': 'حدد منصة متصلة واحدة على الأقل.', 'es-ES': 'Selecciona al menos una plataforma conectada.', 'fr-FR': 'Sélectionnez au moins une plateforme connectée.', 'pt-BR': 'Selecione pelo menos uma plataforma conectada.', 'ru-RU': 'Выберите хотя бы одну подключённую платформу.', 'ur-PK': 'کم از کم ایک جڑا ہوا پلیٹ فارم منتخب کریں۔', 'tr-TR': 'En az bir bağlı platform seçin.' },
  post_err_choose_date: { 'en-US': 'Choose a schedule date first.', 'bn-BD': 'প্রথমে একটি সময়সূচী তারিখ বেছে নিন।', 'hi-IN': 'पहले एक शेड्यूल तारीख चुनें।', 'ar-SA': 'اختر تاريخ الجدولة أولاً.', 'es-ES': 'Elige primero una fecha de programación.', 'fr-FR': 'Choisissez d\'abord une date de programmation.', 'pt-BR': 'Escolha primeiro uma data de agendamento.', 'ru-RU': 'Сначала выберите дату публикации.', 'ur-PK': 'پہلے شیڈول تاریخ منتخب کریں۔', 'tr-TR': 'Önce bir zamanlama tarihi seçin.' },
  post_hdr_ai: { 'en-US': 'AI Generator', 'bn-BD': 'AI জেনারেটর', 'hi-IN': 'AI जेनरेटर', 'ar-SA': 'مولّد الذكاء الاصطناعي', 'es-ES': 'Generador AI', 'fr-FR': 'Générateur IA', 'pt-BR': 'Gerador IA', 'ru-RU': 'ИИ-генератор', 'ur-PK': 'AI جنریٹر', 'tr-TR': 'AI Üreteci' },
  post_no_platforms_short: { 'en-US': 'No publishable connected platforms found.', 'bn-BD': 'কোনো প্রকাশযোগ্য সংযুক্ত প্ল্যাটফর্ম পাওয়া যায়নি।', 'hi-IN': 'कोई प्रকाशनयोग्य जुड़ा प्लेटफ़ॉर्म नहीं मिला।', 'ar-SA': 'لم يتم العثور على منصات متصلة قابلة للنشر.', 'es-ES': 'No se encontraron plataformas conectadas publicables.', 'fr-FR': 'Aucune plateforme connectée publiable trouvée.', 'pt-BR': 'Nenhuma plataforma conectada publicável encontrada.', 'ru-RU': 'Подключённые платформы для публикации не найдены.', 'ur-PK': 'کوئی قابل اشاعت جڑا ہوا پلیٹ فارم نہیں ملا۔', 'tr-TR': 'Yayınlanabilir bağlı platform bulunamadı.' },
  post_characters: { 'en-US': 'characters', 'bn-BD': 'অক্ষর', 'hi-IN': 'अक्षर', 'ar-SA': 'حرف', 'es-ES': 'caracteres', 'fr-FR': 'caractères', 'pt-BR': 'caracteres', 'ru-RU': 'символов', 'ur-PK': 'حروف', 'tr-TR': 'karakter' },
  post_btn_publish_now: { 'en-US': 'Publish Now', 'bn-BD': 'এখনই প্রকাশ করুন', 'hi-IN': 'अभी प्रकाशित करें', 'ar-SA': 'نشر الآن', 'es-ES': 'Publicar Ahora', 'fr-FR': 'Publier Maintenant', 'pt-BR': 'Publicar Agora', 'ru-RU': 'Опубликовать сейчас', 'ur-PK': 'ابھی شائع کریں', 'tr-TR': 'Şimdi Yayınla' },
  post_no_history: { 'en-US': 'No social posts yet.', 'bn-BD': 'এখনো কোনো সোশ্যাল পোস্ট নেই।', 'hi-IN': 'अभी कोई सोशल पोस्ट नहीं।', 'ar-SA': 'لا توجد منشورات اجتماعية بعد.', 'es-ES': 'Aún no hay publicaciones sociales.', 'fr-FR': 'Aucune publication sociale pour l\'instant.', 'pt-BR': 'Ainda não há publicações sociais.', 'ru-RU': 'Социальных публикаций пока нет.', 'ur-PK': 'ابھی کوئی سوشل پوسٹ نہیں۔', 'tr-TR': 'Henüz sosyal gönderi yok.' },

  // Onboarding.jsx
  onboard_role_investor: { 'en-US': 'Real Estate Investor', 'bn-BD': 'রিয়েল এস্টেট বিনিয়োগকারী', 'hi-IN': 'रियल एस्टेट निवेशक', 'ar-SA': 'مستثمر عقاري', 'es-ES': 'Inversor Inmobiliario', 'fr-FR': 'Investisseur Immobilier', 'pt-BR': 'Investidor Imobiliário', 'ru-RU': 'Инвестор в недвижимость', 'ur-PK': 'رئیل اسٹیٹ سرمایہ کار', 'tr-TR': 'Gayrimenkul Yatırımcısı' },
  onboard_role_investor_desc: { 'en-US': 'Looking to find and fund properties.', 'bn-BD': 'সম্পত্তি খুঁজে বের করতে ও অর্থায়ন করতে আগ্রহী।', 'hi-IN': 'संपत्ति खोजने और निधि देने के इच्छुक।', 'ar-SA': 'أبحث عن عقارات وتمويلها.', 'es-ES': 'Buscando encontrar y financiar propiedades.', 'fr-FR': 'À la recherche de propriétés à financer.', 'pt-BR': 'Procurando encontrar e financiar imóveis.', 'ru-RU': 'Ищу и финансирую объекты недвижимости.', 'ur-PK': 'جائیدادیں تلاش اور فنڈ کرنا چاہتے ہیں۔', 'tr-TR': 'Mülk bulmak ve finanse etmek istiyor.' },
  onboard_role_realtor: { 'en-US': 'Realtor / Agent', 'bn-BD': 'রিয়েলটর / এজেন্ট', 'hi-IN': 'रियल्टर / एजेंट', 'ar-SA': 'وكيل عقاري', 'es-ES': 'Agente Inmobiliario', 'fr-FR': 'Agent Immobilier', 'pt-BR': 'Corretor de Imóveis', 'ru-RU': 'Риэлтор / Агент', 'ur-PK': 'ریلٹر / ایجنٹ', 'tr-TR': 'Emlakçı / Ajan' },
  onboard_role_realtor_desc: { 'en-US': 'Managing clients, listings, and leads.', 'bn-BD': 'ক্লায়েন্ট, তালিকা এবং লিড পরিচালনা করছেন।', 'hi-IN': 'ग्राहक, लिस्टिंग और लीड प्रबंधित करना।', 'ar-SA': 'إدارة العملاء والقوائم والعملاء المحتملين.', 'es-ES': 'Gestionando clientes, listados y leads.', 'fr-FR': 'Gestion de clients, annonces et prospects.', 'pt-BR': 'Gerenciando clientes, listagens e leads.', 'ru-RU': 'Управляю клиентами, объявлениями и лидами.', 'ur-PK': 'کلائنٹس، لسٹنگز اور لیڈز مینیج کرنا۔', 'tr-TR': 'Müşterileri, ilanları ve potansiyel müşterileri yönetiyor.' },
  onboard_role_landlord: { 'en-US': 'Landlord', 'bn-BD': 'বাড়িওয়ালা', 'hi-IN': 'मकान मालिक', 'ar-SA': 'مالك العقار', 'es-ES': 'Propietario', 'fr-FR': 'Propriétaire', 'pt-BR': 'Proprietário', 'ru-RU': 'Арендодатель', 'ur-PK': 'مالک مکان', 'tr-TR': 'Ev Sahibi' },
  onboard_role_landlord_desc: { 'en-US': 'Managing rentals and tenant leases.', 'bn-BD': 'ভাড়া এবং ভাড়াটে চুক্তি পরিচালনা করছেন।', 'hi-IN': 'किराये और किरायेदार पट्टे प्रबंधित करना।', 'ar-SA': 'إدارة الإيجارات وعقود المستأجرين.', 'es-ES': 'Gestionando alquileres y arrendamientos de inquilinos.', 'fr-FR': 'Gestion des locations et des baux de locataires.', 'pt-BR': 'Gerenciando aluguéis e contratos de locatários.', 'ru-RU': 'Управляю арендой и договорами с арендаторами.', 'ur-PK': 'کرایوں اور کرایہ دار معاہدوں کا انتظام۔', 'tr-TR': 'Kiralıkları ve kiracı sözleşmelerini yönetiyor.' },
  onboard_role_buyer: { 'en-US': 'Homebuyer', 'bn-BD': 'গৃহ ক্রেতা', 'hi-IN': 'होम खरीदार', 'ar-SA': 'مشتري منزل', 'es-ES': 'Comprador de Vivienda', 'fr-FR': 'Acheteur Immobilier', 'pt-BR': 'Comprador de Imóvel', 'ru-RU': 'Покупатель жилья', 'ur-PK': 'گھر خریدار', 'tr-TR': 'Ev Alıcısı' },
  onboard_role_buyer_desc: { 'en-US': 'Looking for my dream home.', 'bn-BD': 'আমার স্বপ্নের বাড়ি খুঁজছি।', 'hi-IN': 'अपने सपनों का घर ढूंढ रहा हूं।', 'ar-SA': 'أبحث عن منزل أحلامي.', 'es-ES': 'Buscando mi hogar soñado.', 'fr-FR': 'À la recherche de ma maison idéale.', 'pt-BR': 'Procurando minha casa dos sonhos.', 'ru-RU': 'Ищу дом своей мечты.', 'ur-PK': 'اپنے خوابوں کا گھر ڈھونڈ رہا ہوں۔', 'tr-TR': 'Hayalindeki evi arıyor.' },
  onboard_goal_expand: { 'en-US': 'Expand my portfolio', 'bn-BD': 'আমার পোর্টফোলিও সম্প্রসারিত করুন', 'hi-IN': 'अपना पोर्टफोलियो बढ़ाएं', 'ar-SA': 'توسيع محفظتي', 'es-ES': 'Expandir mi cartera', 'fr-FR': 'Développer mon portefeuille', 'pt-BR': 'Expandir meu portfólio', 'ru-RU': 'Расширить портфель', 'ur-PK': 'اپنا پورٹ فولیو بڑھائیں', 'tr-TR': 'Portföyümü genişlet' },
  onboard_goal_leads: { 'en-US': 'Generate more leads', 'bn-BD': 'আরও লিড তৈরি করুন', 'hi-IN': 'अधिक लीड जनरेट करें', 'ar-SA': 'توليد المزيد من العملاء المحتملين', 'es-ES': 'Generar más leads', 'fr-FR': 'Générer plus de prospects', 'pt-BR': 'Gerar mais leads', 'ru-RU': 'Привлекать больше лидов', 'ur-PK': 'زیادہ لیڈز بنائیں', 'tr-TR': 'Daha fazla potansiyel müşteri oluştur' },
  onboard_goal_automate: { 'en-US': 'Automate my workflows', 'bn-BD': 'আমার ওয়ার্কফ্লো স্বয়ংক্রিয় করুন', 'hi-IN': 'अपने वर्कफ़्लो स्वचालित करें', 'ar-SA': 'أتمتة سير العمل لديّ', 'es-ES': 'Automatizar mis flujos de trabajo', 'fr-FR': 'Automatiser mes flux de travail', 'pt-BR': 'Automatizar meus fluxos de trabalho', 'ru-RU': 'Автоматизировать рабочие процессы', 'ur-PK': 'اپنے ورک فلوز کو خودکار بنائیں', 'tr-TR': 'İş akışlarımı otomatikleştir' },
  onboard_goal_network: { 'en-US': 'Network with professionals', 'bn-BD': 'পেশাদারদের সাথে নেটওয়ার্ক করুন', 'hi-IN': 'पेशेवरों के साथ नेटवर्क करें', 'ar-SA': 'التواصل مع المحترفين', 'es-ES': 'Conectar con profesionales', 'fr-FR': 'Réseauter avec des professionnels', 'pt-BR': 'Fazer networking com profissionais', 'ru-RU': 'Налаживать контакты с профессионалами', 'ur-PK': 'پیشہ ور افراد سے نیٹ ورک بنائیں', 'tr-TR': 'Profesyonellerle ağ oluştur' },
  onboard_goal_deals: { 'en-US': 'Find off-market deals', 'bn-BD': 'অফ-মার্কেট ডিল খুঁজুন', 'hi-IN': 'ऑफ-मार्केट डील खोजें', 'ar-SA': 'إيجاد صفقات خارج السوق', 'es-ES': 'Encontrar ofertas fuera del mercado', 'fr-FR': 'Trouver des offres hors marché', 'pt-BR': 'Encontrar negócios fora do mercado', 'ru-RU': 'Искать внебиржевые сделки', 'ur-PK': 'آف مارکیٹ ڈیلز تلاش کریں', 'tr-TR': 'Piyasa dışı fırsatlar bul' },
  onboard_goal_maintenance: { 'en-US': 'Manage property maintenance', 'bn-BD': 'সম্পত্তি রক্ষণাবেক্ষণ পরিচালনা করুন', 'hi-IN': 'संपत्ति रखरखाव प्रबंधित करें', 'ar-SA': 'إدارة صيانة الممتلكات', 'es-ES': 'Gestionar el mantenimiento de propiedades', 'fr-FR': 'Gérer l\'entretien des propriétés', 'pt-BR': 'Gerenciar manutenção de propriedades', 'ru-RU': 'Управлять обслуживанием недвижимости', 'ur-PK': 'جائیداد کی دیکھ بھال مینیج کریں', 'tr-TR': 'Mülk bakımını yönet' },
  onboard_step1_title: { 'en-US': 'Welcome! How do you identify?', 'bn-BD': 'স্বাগতম! আপনি কে হিসেবে নিজেকে পরিচয় দেন?', 'hi-IN': 'स्वागत है! आप खुद को कैसे पहचानते हैं?', 'ar-SA': 'مرحباً! كيف تعرّف عن نفسك؟', 'es-ES': '¡Bienvenido! ¿Cómo te identificas?', 'fr-FR': 'Bienvenue ! Comment vous définissez-vous ?', 'pt-BR': 'Bem-vindo! Como você se identifica?', 'ru-RU': 'Добро пожаловать! Как вы себя позиционируете?', 'ur-PK': 'خوش آمدید! آپ اپنے آپ کو کیسے پہچانتے ہیں؟', 'tr-TR': 'Hoş geldiniz! Kendinizi nasıl tanımlıyorsunuz?' },
  onboard_step1_sub: { 'en-US': 'Select the role that best describes you to personalize your experience.', 'bn-BD': 'আপনার অভিজ্ঞতা ব্যক্তিগতকৃত করতে আপনাকে সবচেয়ে ভালোভাবে বর্ণনা করে এমন ভূমিকা নির্বাচন করুন।', 'hi-IN': 'अपने अनुभव को वैयक्तिकृत करने के लिए वह भूमिका चुनें जो आपको सबसे अच्छी तरह वर्णित करती है।', 'ar-SA': 'حدد الدور الذي يصفك أكثر لتخصيص تجربتك.', 'es-ES': 'Selecciona el rol que mejor te describe para personalizar tu experiencia.', 'fr-FR': 'Sélectionnez le rôle qui vous décrit le mieux pour personnaliser votre expérience.', 'pt-BR': 'Selecione a função que melhor te descreve para personalizar sua experiência.', 'ru-RU': 'Выберите роль, которая лучше всего вас описывает, чтобы персонализировать опыт.', 'ur-PK': 'اپنا تجربہ ذاتی بنانے کے لیے وہ کردار منتخب کریں جو آپ کو بہترین طریقے سے بیان کرتا ہو۔', 'tr-TR': 'Deneyiminizi kişiselleştirmek için sizi en iyi tanımlayan rolü seçin.' },
  onboard_step2_title: { 'en-US': 'What are your main goals?', 'bn-BD': 'আপনার প্রধান লক্ষ্যগুলো কী?', 'hi-IN': 'आपके मुख्य लक्ष्य क्या हैं?', 'ar-SA': 'ما هي أهدافك الرئيسية؟', 'es-ES': '¿Cuáles son tus objetivos principales?', 'fr-FR': 'Quels sont vos principaux objectifs ?', 'pt-BR': 'Quais são seus principais objetivos?', 'ru-RU': 'Каковы ваши главные цели?', 'ur-PK': 'آپ کے اہم اہداف کیا ہیں؟', 'tr-TR': 'Ana hedefleriniz nelerdir?' },
  onboard_step2_sub: { 'en-US': 'Select all that apply. We\'ll tailor your dashboard based on this.', 'bn-BD': 'প্রযোজ্য সব নির্বাচন করুন। এর উপর ভিত্তি করে আমরা আপনার ড্যাশবোর্ড কাস্টমাইজ করব।', 'hi-IN': 'जो भी लागू हो चुनें। इसके आधार पर हम आपका डैशबोर्ड तैयार करेंगे।', 'ar-SA': 'حدد كل ما ينطبق. سنخصص لوحة التحكم الخاصة بك بناءً على هذا.', 'es-ES': 'Selecciona todo lo que corresponda. Adaptaremos tu panel basándonos en esto.', 'fr-FR': 'Sélectionnez tout ce qui s\'applique. Nous personnaliserons votre tableau de bord en conséquence.', 'pt-BR': 'Selecione tudo que se aplica. Vamos personalizar seu painel com base nisso.', 'ru-RU': 'Выберите всё, что подходит. Мы настроим ваш дашборд на основе этого.', 'ur-PK': 'جو بھی لاگو ہو منتخب کریں۔ ہم اس بنیاد پر آپ کا ڈیش بورڈ تیار کریں گے۔', 'tr-TR': 'Geçerli olanları seçin. Buna göre panelinizi özelleştireceğiz.' },
  onboard_step3_title: { 'en-US': 'Just a few more details', 'bn-BD': 'আরও কিছু বিবরণ', 'hi-IN': 'कुछ और विवरण', 'ar-SA': 'بعض التفاصيل الإضافية', 'es-ES': 'Solo unos pocos detalles más', 'fr-FR': 'Encore quelques détails', 'pt-BR': 'Mais alguns detalhes', 'ru-RU': 'Ещё несколько деталей', 'ur-PK': 'چند مزید تفصیلات', 'tr-TR': 'Birkaç ayrıntı daha' },
  onboard_step3_sub: { 'en-US': 'Help us complete your professional profile.', 'bn-BD': 'আপনার পেশাদার প্রোফাইল সম্পন্ন করতে আমাদের সাহায্য করুন।', 'hi-IN': 'अपनी पेशेवर प्रोफ़ाइल पूरी करने में हमारी मदद करें।', 'ar-SA': 'ساعدنا في إكمال ملفك الشخصي المهني.', 'es-ES': 'Ayúdanos a completar tu perfil profesional.', 'fr-FR': 'Aidez-nous à compléter votre profil professionnel.', 'pt-BR': 'Ajude-nos a completar seu perfil profissional.', 'ru-RU': 'Помогите нам завершить ваш профессиональный профиль.', 'ur-PK': 'اپنا پیشہ ورانہ پروفائل مکمل کرنے میں ہماری مدد کریں۔', 'tr-TR': 'Profesyonel profilinizi tamamlamamıza yardımcı olun.' },
  onboard_lbl_company: { 'en-US': 'Company Name (Optional)', 'bn-BD': 'কোম্পানির নাম (ঐচ্ছিক)', 'hi-IN': 'कंपनी का नाम (वैकल्पिक)', 'ar-SA': 'اسم الشركة (اختياري)', 'es-ES': 'Nombre de Empresa (Opcional)', 'fr-FR': 'Nom de l\'Entreprise (Optionnel)', 'pt-BR': 'Nome da Empresa (Opcional)', 'ru-RU': 'Название компании (необязательно)', 'ur-PK': 'کمپنی کا نام (اختیاری)', 'tr-TR': 'Şirket Adı (İsteğe Bağlı)' },
  onboard_ph_company: { 'en-US': 'e.g. Acme Real Estate', 'bn-BD': 'যেমন: Acme Real Estate', 'hi-IN': 'जैसे: Acme Real Estate', 'ar-SA': 'مثال: Acme Real Estate', 'es-ES': 'ej. Acme Real Estate', 'fr-FR': 'ex. Acme Real Estate', 'pt-BR': 'ex. Acme Real Estate', 'ru-RU': 'напр. Acme Real Estate', 'ur-PK': 'مثلاً: Acme Real Estate', 'tr-TR': 'örn. Acme Gayrimenkul' },
  onboard_lbl_experience: { 'en-US': 'Years of Experience', 'bn-BD': 'অভিজ্ঞতার বছর', 'hi-IN': 'अनुभव के वर्ष', 'ar-SA': 'سنوات الخبرة', 'es-ES': 'Años de Experiencia', 'fr-FR': 'Années d\'Expérience', 'pt-BR': 'Anos de Experiência', 'ru-RU': 'Лет опыта', 'ur-PK': 'تجربے کے سال', 'tr-TR': 'Deneyim Yılları' },
  onboard_exp_lt1: { 'en-US': 'Less than 1 year', 'bn-BD': '১ বছরের কম', 'hi-IN': '1 साल से कम', 'ar-SA': 'أقل من سنة', 'es-ES': 'Menos de 1 año', 'fr-FR': 'Moins d\'1 an', 'pt-BR': 'Menos de 1 ano', 'ru-RU': 'Менее 1 года', 'ur-PK': '1 سال سے کم', 'tr-TR': '1 yıldan az' },
  onboard_exp_1_3: { 'en-US': '1-3 years', 'bn-BD': '১-৩ বছর', 'hi-IN': '1-3 साल', 'ar-SA': '1-3 سنوات', 'es-ES': '1-3 años', 'fr-FR': '1-3 ans', 'pt-BR': '1-3 anos', 'ru-RU': '1-3 года', 'ur-PK': '1-3 سال', 'tr-TR': '1-3 yıl' },
  onboard_exp_3_5: { 'en-US': '3-5 years', 'bn-BD': '৩-৫ বছর', 'hi-IN': '3-5 साल', 'ar-SA': '3-5 سنوات', 'es-ES': '3-5 años', 'fr-FR': '3-5 ans', 'pt-BR': '3-5 anos', 'ru-RU': '3-5 лет', 'ur-PK': '3-5 سال', 'tr-TR': '3-5 yıl' },
  onboard_exp_5_10: { 'en-US': '5-10 years', 'bn-BD': '৫-১০ বছর', 'hi-IN': '5-10 साल', 'ar-SA': '5-10 سنوات', 'es-ES': '5-10 años', 'fr-FR': '5-10 ans', 'pt-BR': '5-10 anos', 'ru-RU': '5-10 лет', 'ur-PK': '5-10 سال', 'tr-TR': '5-10 yıl' },
  onboard_exp_10plus: { 'en-US': '10+ years', 'bn-BD': '১০+ বছর', 'hi-IN': '10+ साल', 'ar-SA': 'أكثر من 10 سنوات', 'es-ES': '10+ años', 'fr-FR': '10+ ans', 'pt-BR': '10+ anos', 'ru-RU': '10+ лет', 'ur-PK': '10+ سال', 'tr-TR': '10+ yıl' },
  onboard_btn_back: { 'en-US': 'Back', 'bn-BD': 'পিছনে', 'hi-IN': 'वापस', 'ar-SA': 'رجوع', 'es-ES': 'Atrás', 'fr-FR': 'Retour', 'pt-BR': 'Voltar', 'ru-RU': 'Назад', 'ur-PK': 'واپس', 'tr-TR': 'Geri' },
  onboard_finishing: { 'en-US': 'Finishing...', 'bn-BD': 'সম্পন্ন হচ্ছে...', 'hi-IN': 'पूरा हो रहा है...', 'ar-SA': 'جارٍ الإنهاء...', 'es-ES': 'Finalizando...', 'fr-FR': 'Finalisation...', 'pt-BR': 'Finalizando...', 'ru-RU': 'Завершение...', 'ur-PK': 'مکمل ہو رہا ہے...', 'tr-TR': 'Tamamlanıyor...' },
  onboard_btn_dashboard: { 'en-US': 'Go to Dashboard', 'bn-BD': 'ড্যাশবোর্ডে যান', 'hi-IN': 'डैशबोर्ड पर जाएं', 'ar-SA': 'الذهاب إلى لوحة التحكم', 'es-ES': 'Ir al Panel', 'fr-FR': 'Aller au Tableau de Bord', 'pt-BR': 'Ir para o Painel', 'ru-RU': 'Перейти в дашборд', 'ur-PK': 'ڈیش بورڈ پر جائیں', 'tr-TR': 'Panele Git' },
  onboard_btn_continue: { 'en-US': 'Continue', 'bn-BD': 'চালিয়ে যান', 'hi-IN': 'जारी रखें', 'ar-SA': 'متابعة', 'es-ES': 'Continuar', 'fr-FR': 'Continuer', 'pt-BR': 'Continuar', 'ru-RU': 'Продолжить', 'ur-PK': 'جاری رکھیں', 'tr-TR': 'Devam Et' },
};

const filePath = 'c:/project/Mabdel AI/Mabdel Website/src/i18n/translations.js';
let content = fs.readFileSync(filePath, 'utf-8');

const langs = ['en-US', 'bn-BD', 'hi-IN', 'ar-SA', 'es-ES', 'fr-FR', 'pt-BR', 'ru-RU', 'ur-PK', 'tr-TR'];

// Skip keys already present in the entire file once (for en-US)
// But for other blocks we need per-block checking
for (const lang of langs) {
  const targetTag = `'${lang}': {`;
  const pos = content.indexOf(targetTag);
  if (pos === -1) {
    console.error(`Could not find block for ${lang}`);
    process.exit(1);
  }

  // Find the end of this language block
  const blockEndPos = content.indexOf('\n  },', pos);

  // Extract this language block as a substring for checking
  const blockContent = content.slice(pos, blockEndPos);

  const keysToAdd = Object.entries(translations).filter(([k]) => {
    return !blockContent.includes(`    ${k}:`);
  });

  if (!keysToAdd.length) {
    console.log(`${lang}: all keys already present, skipping.`);
    continue;
  }

  const keyLines = keysToAdd
    .map(([k, vals]) => `    ${k}: ${JSON.stringify(vals[lang] || vals['en-US'])},`)
    .join('\n');

  content = content.slice(0, blockEndPos) + keyLines + '\n' + content.slice(blockEndPos);
  console.log(`${lang}: appended ${keysToAdd.length} keys.`);
}


fs.writeFileSync(filePath, content, 'utf-8');
console.log(`Done!`);
