import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import {
  Apple,
  ArrowRight,
  Bot,
  CalendarClock,
  Check,
  CreditCard,
  Cpu,
  FileSignature,
  FileText,
  Inbox,
  Lock,
  Megaphone,
  MessageSquare,
  Mic,
  PhoneCall,
  Play,
  Send,
  Share2,
  Sparkles,
  TrendingUp,
  Users,
  X,
} from 'lucide-react';
import heroImage from '../assets/hero-3d.png';
import logoMark from '../assets/gocustify-mark.png';

// TODO: paste your YouTube/Vimeo embed URL here, e.g. 'https://www.youtube.com/embed/VIDEO_ID'
const DEMO_VIDEO_EMBED_URL = '';

function StoreBadge({ icon: Icon, eyebrow, label, compact = false }) {
  return (
    <button
      type="button"
      onClick={() => window.alert(`${label} is coming soon.`)}
      className={`flex items-center gap-2.5 bg-gray-900/60 hover:bg-gray-900 border border-gray-800 hover:border-gray-700 rounded-xl transition-all cursor-pointer text-left ${
        compact ? 'px-3.5 py-2' : 'px-4 py-2.5'
      }`}
    >
      <Icon size={compact ? 18 : 22} className="text-white shrink-0" />
      <span className="leading-tight">
        <span className={`block font-medium text-gray-400 uppercase tracking-wide ${compact ? 'text-[8px]' : 'text-[9px]'}`}>{eyebrow}</span>
        <span className={`block font-bold text-white ${compact ? 'text-xs' : 'text-sm'}`}>{label}</span>
      </span>
      <span className="ml-1 text-[9px] font-bold uppercase tracking-wider text-cyan-400 border border-cyan-500/30 bg-cyan-950/30 rounded-full px-2 py-0.5">
        Soon
      </span>
    </button>
  );
}

const stats = [
  { value: '24/7', label: 'AI receptionist answering calls & SMS' },
  { value: '8+', label: 'Channels unified in one inbox' },
  { value: '3,000+', label: 'AI call minutes on Pro every month' },
  { value: '7 Days', label: 'Free trial — no commitment' },
];

const journeyTabs = [
  {
    id: 'capture',
    label: 'Capture',
    icon: PhoneCall,
    title: 'Never miss another lead',
    description:
      'Your AI receptionist answers every call and text, books appointments, and files every lead straight into your CRM — even while you sleep.',
    bullets: [
      'AI receptionist handles calls + SMS around the clock',
      'Missed-call text back wins the lead before a competitor does',
      'CRM with leads, contacts, and pipeline built in',
      'Calendar booking & scheduling without back-and-forth',
    ],
    panel: {
      icon: Mic,
      eyebrow: 'AI Receptionist',
      headline: 'Incoming call answered',
      detail: '"Booked Sarah for Tuesday 2:30 PM and added her to your pipeline."',
    },
  },
  {
    id: 'engage',
    label: 'Engage',
    icon: MessageSquare,
    title: 'Every conversation in one place',
    description:
      'Facebook, Instagram, WhatsApp, Telegram, SMS, and email flow into one team inbox — and AI drafts the replies so nothing sits unanswered.',
    bullets: [
      'Unified team inbox across social, SMS, and email',
      'AI reads & responds to messages on FB, IG, and X',
      'AI auto-replies to comments on your social posts',
      'Bulk SMS and email campaigns with scheduling',
    ],
    panel: {
      icon: Inbox,
      eyebrow: 'Unified Inbox',
      headline: '3 new conversations',
      detail: 'AI drafted replies for Instagram, WhatsApp, and SMS — review and send.',
    },
  },
  {
    id: 'close',
    label: 'Close',
    icon: FileSignature,
    title: 'From conversation to paid — automatically',
    description:
      'Say "invoice Sarah $500 for the homepage" and AI generates the invoice, the agreement, and the e-signature request. You just watch it get signed.',
    bullets: [
      'AI invoice generation, delivery, and payment tracking',
      'Proposals, agreements & leases generated by AI',
      'E-signatures with shareable signing links & PDFs',
      'Voice-to-workflow: speak it, and it is created',
    ],
    panel: {
      icon: CreditCard,
      eyebrow: 'Smart Invoicing',
      headline: 'Invoice #AGR-1042 signed & paid',
      detail: 'Sent, signed, and settled — receipt emailed automatically.',
    },
  },
  {
    id: 'grow',
    label: 'Grow',
    icon: TrendingUp,
    title: 'Marketing that runs itself',
    description:
      'AI writes your social posts and marketing content, publishes across platforms, and your call analytics show exactly what is working.',
    bullets: [
      'AI social media post creation & multi-platform publishing',
      'AI marketing content generation on demand',
      'AI call analytics and conversation summaries',
      'Advanced automation workflows tie it all together',
    ],
    panel: {
      icon: Share2,
      eyebrow: 'AI Publisher',
      headline: 'Post published to 3 platforms',
      detail: 'Facebook, Instagram, and LinkedIn — auto-replies switched on.',
    },
  },
];

const bentoCards = [
  {
    title: 'AI Voice Assistant',
    description: 'Talk to your business. Live transcription, AI chat, and voice commands that create invoices, meetings, and campaigns.',
    icon: Mic,
  },
  {
    title: 'Smart Invoicing',
    description: 'AI auto-fills client details, generates line items, and sends automatically. Track status in real-time.',
    icon: FileText,
  },
  {
    title: 'Unified Inbox',
    description: 'Facebook, Instagram, WhatsApp, Telegram, SMS, and email in one place — with AI-drafted responses.',
    icon: MessageSquare,
  },
  {
    title: 'Bulk Campaigns',
    description: 'Bulk SMS and email campaigns with recipient validation, scheduling, and delivery tracking.',
    icon: Send,
  },
  {
    title: 'Documents & E-Sign',
    description: 'AI-generated proposals, agreements, and leases with shareable signing links and instant PDFs.',
    icon: FileSignature,
  },
  {
    title: 'Team & Automation',
    description: 'Unlimited users on Growth, role-based access, shared inbox, and workflows that finish the follow-up for you.',
    icon: Cpu,
  },
];

const pricingPlans = [
  {
    name: 'Starter',
    price: '$299',
    subtitle: 'Best for solo business owners',
    features: [
      '1 user',
      'AI receptionist (calls + SMS)',
      'CRM: leads, contacts, pipeline',
      'Calendar booking & scheduling',
      'Missed-call text back',
      '300 call min · 500 SMS · 200 emails',
    ],
  },
  {
    name: 'Growth',
    price: '$699',
    subtitle: 'Best for small businesses ready to scale',
    isPopular: true,
    features: [
      'Everything in Starter',
      'Unlimited users & team inbox',
      'Facebook + Instagram messaging',
      'AI auto-replies on social media',
      'Bulk SMS & email campaigns',
      '1,500 call min · 5,000 SMS · 10,000 emails',
    ],
  },
  {
    name: 'Pro',
    price: '$999',
    subtitle: 'Best for growing & operating businesses',
    features: [
      'Everything in Growth',
      'Invoice generation & billing tools',
      'Agreements, contracts & e-signatures',
      'Advanced automation workflows',
      'Priority support',
      '3,000 call min · 15,000 SMS · 50,000 emails',
    ],
  },
];

export default function Landing() {
  const navigate = useNavigate();
  const [videoOpen, setVideoOpen] = useState(false);

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.15,
      },
    },
  };

  const itemVariants = {
    hidden: { y: 30, opacity: 0 },
    visible: {
      y: 0,
      opacity: 1,
      transition: { duration: 0.6, ease: 'easeOut' },
    },
  };

  const TrialButton = ({ className = '' }) => (
    <button
      onClick={() => navigate('/subscription')}
      className={`px-8 py-4 bg-gradient-to-r from-cyan-400 to-teal-400 text-[#070a13] font-bold rounded-xl shadow-lg shadow-cyan-500/20 hover:opacity-95 hover:shadow-cyan-500/35 transition-all active:scale-[0.98] inline-flex items-center justify-center gap-2 group ${className}`}
    >
      Start 7-Day Free Trial
      <ArrowRight size={18} className="group-hover:translate-x-1 transition-transform" />
    </button>
  );

  return (
    <div className="min-h-screen bg-[#070a13] text-gray-100 font-sans antialiased overflow-x-hidden selection:bg-cyan-500 selection:text-[#070a13]">

      {/* Background Gradients */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-7xl h-[600px] pointer-events-none -z-10 overflow-hidden">
        <div className="absolute top-[-10%] left-[20%] w-[60%] h-[80%] bg-gradient-to-tr from-cyan-500/10 to-teal-500/5 rounded-full blur-[120px] opacity-75" />
        <div className="absolute top-[20%] right-[10%] w-[40%] h-[60%] bg-cyan-600/5 rounded-full blur-[100px] opacity-50" />
      </div>

      {/* Header */}
      <header className="sticky top-0 z-50 backdrop-blur-md border-b border-gray-900 bg-[#070a13]/70">
        <div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
          <div className="flex items-center gap-2 cursor-pointer" onClick={() => navigate('/')}>
            <img src={logoMark} alt="GoCustify logo" className="w-9 h-9 rounded-lg shadow-lg shadow-cyan-500/20" />
            <span className="text-xl font-bold tracking-tight text-white bg-clip-text">GoCustify</span>
          </div>

          <nav className="hidden md:flex items-center gap-8 text-sm font-medium text-gray-400">
            <a href="#journey" className="hover:text-white transition-colors">How It Works</a>
            <a href="#features" className="hover:text-white transition-colors">Features</a>
            <a href="#pricing" className="hover:text-white transition-colors">Pricing</a>
          </nav>

          <div className="flex items-center gap-4">
            <button
              onClick={() => navigate('/login')}
              className="px-5 py-2.5 text-sm font-semibold text-gray-300 hover:text-white border border-gray-800 hover:border-gray-700 rounded-xl transition-all"
            >
              Login
            </button>
            <button
              onClick={() => navigate('/subscription')}
              className="px-5 py-2.5 text-sm font-semibold bg-gradient-to-r from-cyan-400 to-teal-400 text-[#070a13] rounded-xl hover:opacity-90 transition-all shadow-lg shadow-cyan-500/10 hover:shadow-cyan-500/25 active:scale-[0.98]"
            >
              Start Free Trial
            </button>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="relative pt-12 pb-24 md:py-32">
        <div className="max-w-7xl mx-auto px-6 grid grid-cols-1 lg:grid-cols-12 gap-16 items-center">

          {/* Left Text */}
          <div className="lg:col-span-7 flex flex-col items-start text-left space-y-8">
            <motion.div
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
              className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-cyan-500/30 bg-cyan-950/20 text-cyan-400 text-xs font-semibold uppercase tracking-wider"
            >
              <Sparkles size={12} className="animate-pulse" /> The AI-Powered Business Operating System
            </motion.div>

            <motion.h1
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.1 }}
              className="text-4xl sm:text-5xl md:text-6xl font-extrabold tracking-tight leading-[1.1] text-white"
            >
              Power Up Your <br />
              <span className="bg-gradient-to-r from-cyan-400 via-teal-300 to-cyan-400 bg-clip-text text-transparent">
                Business With AI
              </span>
            </motion.h1>

            <motion.p
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.2 }}
              className="text-lg md:text-xl text-gray-400 max-w-xl font-normal leading-relaxed"
            >
              One platform that answers your calls, replies to your messages, sends your invoices,
              signs your documents, and runs your marketing — so you can run your business.
            </motion.p>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.3 }}
              className="flex flex-wrap gap-4 w-full sm:w-auto"
            >
              <TrialButton className="w-full sm:w-auto" />
              <a
                href="#journey"
                className="px-8 py-4 bg-gray-900/50 hover:bg-gray-900 border border-gray-800 hover:border-gray-700 font-bold rounded-xl text-white transition-all text-center w-full sm:w-auto"
              >
                See How It Works
              </a>
            </motion.div>

            <motion.p
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.6, delay: 0.45 }}
              className="text-xs text-gray-600 font-semibold uppercase tracking-wider"
            >
              7-day free trial · Cancel anytime
            </motion.p>

            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.55 }}
              className="flex flex-wrap gap-3"
            >
              <StoreBadge icon={Apple} eyebrow="Download on the" label="App Store" compact />
              <StoreBadge icon={Play} eyebrow="GET IT ON" label="Google Play" compact />
            </motion.div>
          </div>

          {/* Right Visual (Glowing 3D Mesh & Floating Labels) */}
          <div className="lg:col-span-5 relative flex items-center justify-center">

            {/* Ambient Backlight */}
            <div className="absolute w-72 h-72 bg-cyan-500/10 rounded-full blur-[80px] -z-10 animate-pulse" />

            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.8, delay: 0.2 }}
              className="relative w-full max-w-[400px] aspect-square rounded-full flex items-center justify-center"
            >
              <img
                src={heroImage}
                alt="GoCustify AI Graphic"
                className="w-full h-full object-contain filter drop-shadow-[0_0_50px_rgba(6,182,212,0.15)]"
              />

              {/* Floating Tag 1: Call Answered */}
              <motion.div
                animate={{ y: [0, -10, 0] }}
                transition={{ duration: 4, repeat: Infinity, ease: 'easeInOut' }}
                className="absolute top-12 -left-8 px-4 py-3 bg-[#0d1222]/80 backdrop-blur-md border border-gray-800 rounded-xl flex items-center gap-3 shadow-xl"
              >
                <div className="w-8 h-8 rounded-lg bg-cyan-950 flex items-center justify-center text-cyan-400">
                  <PhoneCall size={16} />
                </div>
                <div className="text-left">
                  <p className="text-[10px] font-bold text-gray-500 uppercase tracking-wider">AI Receptionist</p>
                  <p className="text-xs font-bold text-white">Call Answered & Booked</p>
                </div>
              </motion.div>

              {/* Floating Tag 2: Invoice Paid */}
              <motion.div
                animate={{ y: [0, 8, 0] }}
                transition={{ duration: 3.5, repeat: Infinity, ease: 'easeInOut', delay: 0.5 }}
                className="absolute bottom-20 -right-8 px-4 py-3 bg-[#0d1222]/80 backdrop-blur-md border border-gray-800 rounded-xl flex items-center gap-3 shadow-xl"
              >
                <div className="w-8 h-8 rounded-lg bg-teal-950 flex items-center justify-center text-teal-400">
                  <CreditCard size={16} />
                </div>
                <div className="text-left">
                  <p className="text-[10px] font-bold text-gray-500 uppercase tracking-wider">Smart Invoicing</p>
                  <p className="text-xs font-bold text-white">Invoice Sent & Paid</p>
                </div>
              </motion.div>

              {/* Floating Tag 3: AI Replied */}
              <motion.div
                animate={{ y: [0, -8, 0] }}
                transition={{ duration: 4.5, repeat: Infinity, ease: 'easeInOut', delay: 1 }}
                className="absolute -bottom-4 left-10 px-4 py-3 bg-[#0d1222]/80 backdrop-blur-md border border-gray-800 rounded-xl flex items-center gap-3 shadow-xl"
              >
                <div className="w-8 h-8 rounded-lg bg-cyan-950 flex items-center justify-center text-cyan-400">
                  <Bot size={16} />
                </div>
                <div className="text-left">
                  <p className="text-[10px] font-bold text-gray-500 uppercase tracking-wider">Unified Inbox</p>
                  <p className="text-xs font-bold text-white">AI Replied on Instagram</p>
                </div>
              </motion.div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Demo Video Section */}
      <section className="pb-24 md:pb-32">
        <div className="max-w-5xl mx-auto px-6">
          <div className="text-center mb-10 space-y-3">
            <h2 className="text-2xl md:text-3xl font-extrabold tracking-tight text-white">
              See GoCustify in Action
            </h2>
            <p className="text-gray-400 max-w-xl mx-auto">
              Watch how AI answers calls, replies to messages, and closes deals - all from one platform.
            </p>
          </div>

          <button
            type="button"
            onClick={() => setVideoOpen(true)}
            className="group relative w-full aspect-video rounded-3xl overflow-hidden border border-gray-800 hover:border-cyan-500/40 transition-all shadow-2xl shadow-black/40 cursor-pointer"
          >
            <img
              src={heroImage}
              alt="GoCustify product demo"
              className="w-full h-full object-cover opacity-40 group-hover:opacity-50 transition-opacity"
            />
            <div className="absolute inset-0 bg-gradient-to-b from-[#070a13]/40 via-[#070a13]/60 to-[#070a13]/80" />
            <div className="absolute inset-0 flex items-center justify-center">
              <div className="w-20 h-20 rounded-full bg-cyan-400 text-[#02080B] flex items-center justify-center shadow-xl shadow-cyan-500/30 group-hover:scale-110 transition-transform">
                <Play size={28} fill="currentColor" className="ml-1" />
              </div>
            </div>
            <span className="absolute bottom-5 left-1/2 -translate-x-1/2 text-xs font-bold uppercase tracking-wider text-gray-300">
              Watch 2-min demo
            </span>
          </button>
        </div>
      </section>

      {/* Video Modal */}
      <AnimatePresence>
        {videoOpen && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[200] flex items-center justify-center bg-black/85 backdrop-blur-sm px-4"
            onClick={() => setVideoOpen(false)}
          >
            <motion.div
              initial={{ opacity: 0, scale: 0.96 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.96 }}
              className="relative w-full max-w-4xl aspect-video bg-[#0a0e1a] rounded-2xl overflow-hidden border border-gray-800"
              onClick={(e) => e.stopPropagation()}
            >
              <button
                type="button"
                onClick={() => setVideoOpen(false)}
                className="absolute top-3 right-3 z-10 w-9 h-9 rounded-full bg-black/60 hover:bg-black/80 text-white flex items-center justify-center transition-colors cursor-pointer"
              >
                <X size={16} />
              </button>
              {DEMO_VIDEO_EMBED_URL ? (
                <iframe
                  src={DEMO_VIDEO_EMBED_URL}
                  title="GoCustify demo video"
                  className="w-full h-full"
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                  allowFullScreen
                />
              ) : (
                <div className="w-full h-full flex flex-col items-center justify-center gap-3 text-center px-6">
                  <div className="w-16 h-16 rounded-full bg-gray-900 border border-gray-800 flex items-center justify-center text-gray-600">
                    <Play size={22} fill="currentColor" />
                  </div>
                  <p className="text-gray-400 font-semibold">Demo video coming soon</p>
                </div>
              )}
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Stats Bar */}
      <section className="border-y border-gray-900 bg-[#0a0e1a]/60">
        <div className="max-w-7xl mx-auto px-6 py-12 grid grid-cols-2 lg:grid-cols-4 gap-8">
          {stats.map((stat) => (
            <div key={stat.label} className="text-center space-y-2">
              <p className="text-3xl md:text-4xl font-extrabold bg-gradient-to-r from-cyan-400 to-teal-300 bg-clip-text text-transparent">
                {stat.value}
              </p>
              <p className="text-xs md:text-sm text-gray-500 font-medium leading-snug max-w-[200px] mx-auto">
                {stat.label}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* How It Works (Capture → Engage → Close → Grow) */}
      <section id="journey" className="py-24 md:py-32">
        <div className="max-w-7xl mx-auto px-6 space-y-20 md:space-y-28">
          <div className="text-center space-y-4">
            <h2 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
              One Platform. Your Entire Customer Journey.
            </h2>
            <p className="text-lg text-gray-400 max-w-2xl mx-auto font-normal">
              From the first missed call to the signed agreement — GoCustify handles every step.
            </p>
          </div>

          <div className="space-y-20 md:space-y-28">
            {journeyTabs.map((step, index) => {
              const reversed = index % 2 === 1;
              return (
                <motion.div
                  key={step.id}
                  variants={itemVariants}
                  initial="hidden"
                  whileInView="visible"
                  viewport={{ once: true, margin: '-100px' }}
                  className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center"
                >
                  <div className={`space-y-6 text-left ${reversed ? 'lg:order-2' : 'lg:order-1'}`}>
                    <div className="flex items-center gap-3">
                      <span className="w-10 h-10 rounded-xl bg-gradient-to-r from-cyan-400 to-teal-400 text-[#070a13] font-extrabold flex items-center justify-center text-sm shrink-0">
                        {String(index + 1).padStart(2, '0')}
                      </span>
                      <span className="inline-flex items-center gap-1.5 text-xs font-bold uppercase tracking-widest text-cyan-400">
                        <step.icon size={13} /> {step.label}
                      </span>
                    </div>
                    <h3 className="text-2xl md:text-3xl font-extrabold text-white tracking-tight">
                      {step.title}
                    </h3>
                    <p className="text-gray-400 leading-relaxed">
                      {step.description}
                    </p>
                    <ul className="space-y-3">
                      {step.bullets.map((bullet) => (
                        <li key={bullet} className="flex items-start gap-3 text-sm text-gray-300">
                          <span className="mt-0.5 w-5 h-5 rounded-full bg-cyan-950 border border-cyan-500/30 flex items-center justify-center shrink-0">
                            <Check size={12} className="text-cyan-400" />
                          </span>
                          {bullet}
                        </li>
                      ))}
                    </ul>
                  </div>

                  {/* Illustrative panel */}
                  <div className={`relative flex items-center justify-center py-4 ${reversed ? 'lg:order-1' : 'lg:order-2'}`}>
                    <div className="absolute w-56 h-56 bg-cyan-500/10 rounded-full blur-[70px] -z-0" />
                    <div className="relative z-10 w-full max-w-sm bg-[#0d1222]/90 backdrop-blur-md border border-gray-800 rounded-2xl p-6 shadow-2xl space-y-4">
                      <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-xl bg-cyan-950 border border-cyan-500/20 flex items-center justify-center text-cyan-400">
                          <step.panel.icon size={18} />
                        </div>
                        <p className="text-[10px] font-bold text-gray-500 uppercase tracking-wider">
                          {step.panel.eyebrow}
                        </p>
                      </div>
                      <p className="text-lg font-bold text-white">{step.panel.headline}</p>
                      <p className="text-sm text-gray-400 leading-relaxed">{step.panel.detail}</p>
                      <div className="flex items-center gap-2 pt-2 border-t border-gray-800">
                        <span className="w-2 h-2 rounded-full bg-teal-400 animate-pulse" />
                        <p className="text-[11px] font-semibold text-teal-400">Handled automatically by GoCustify AI</p>
                      </div>
                    </div>
                  </div>
                </motion.div>
              );
            })}
          </div>

          <div className="text-center">
            <TrialButton />
          </div>
        </div>
      </section>

      {/* Pain Point Section */}
      <section className="py-20 border-t border-gray-950 bg-gradient-to-b from-[#070a13] to-[#0a0e1a]">
        <div className="max-w-4xl mx-auto px-6 text-center space-y-8">
          <h2 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
            Stop Duct-Taping Your Business Together
          </h2>
          <p className="text-lg text-gray-400 max-w-2xl mx-auto font-normal leading-relaxed">
            A phone system here, an invoicing tool there, five social inboxes everywhere.
            Scattered tools mean missed leads, late payments, and hours lost every single week.
          </p>

          <div className="flex flex-wrap items-center justify-center gap-4 pt-4">
            {['Missed Calls & Leads', 'Late Payments', 'Scattered Inboxes', 'Manual Follow-Up'].map((pain) => (
              <span
                key={pain}
                className="px-5 py-2 border border-rose-500/20 bg-rose-950/10 text-rose-400 rounded-full text-sm font-semibold flex items-center gap-2 shadow-lg shadow-rose-950/5 cursor-default hover:border-rose-500/35 transition-colors"
              >
                <span className="text-rose-500">✕</span> {pain}
              </span>
            ))}
          </div>

          <p className="text-sm font-bold text-cyan-400 uppercase tracking-widest pt-2">
            GoCustify replaces them all — with one AI that never clocks out.
          </p>
        </div>
      </section>

      {/* Features Bento Grid */}
      <section id="features" className="py-24 md:py-32 bg-[#0a0e1a]">
        <div className="max-w-7xl mx-auto px-6 space-y-16">

          <div className="text-center space-y-4">
            <h2 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
              Everything Your Business Needs. Nothing It Doesn't.
            </h2>
            <p className="text-lg text-gray-400 max-w-2xl mx-auto font-normal">
              Every tool below is included — no add-on marketplace, no per-feature upsells.
            </p>
          </div>

          <motion.div
            variants={containerVariants}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: '-100px' }}
            className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8"
          >
            {bentoCards.map((card, i) => (
              <motion.div
                key={i}
                variants={itemVariants}
                whileHover={{ y: -6 }}
                onClick={() => navigate('/login')}
                className="group relative bg-[#111625]/40 backdrop-blur-xl border border-gray-900 hover:border-cyan-500/40 p-8 rounded-3xl cursor-pointer transition-all duration-300 hover:shadow-[0_0_30px_-5px_rgba(6,182,212,0.15)] flex flex-col justify-between h-72"
              >
                <div className="absolute inset-0 bg-gradient-to-tr from-cyan-500/0 to-cyan-500/5 rounded-3xl opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none duration-300" />

                <div>
                  <div className="w-12 h-12 bg-gray-900 border border-gray-800 rounded-2xl flex items-center justify-center text-cyan-400 group-hover:text-cyan-300 group-hover:border-cyan-500/30 transition-colors">
                    <card.icon size={22} />
                  </div>
                  <h3 className="text-xl font-bold text-white mt-6 group-hover:text-cyan-300 transition-colors">
                    {card.title}
                  </h3>
                  <p className="text-sm text-gray-400 mt-3 font-normal leading-relaxed">
                    {card.description}
                  </p>
                </div>

                <div className="inline-flex items-center gap-2 text-sm font-bold text-cyan-400 group-hover:text-cyan-300 mt-6 select-none">
                  Explore <ArrowRight size={14} className="group-hover:translate-x-1 transition-transform" />
                </div>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-24 md:py-32 border-t border-gray-950">
        <div className="max-w-7xl mx-auto px-6 space-y-16">
          <div className="text-center space-y-4">
            <h2 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
              Simple Pricing. Serious Firepower.
            </h2>
            <p className="text-lg text-gray-400 max-w-2xl mx-auto font-normal">
              Every plan starts with a 7-day free trial. Upgrade, downgrade, or cancel anytime.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 items-stretch">
            {pricingPlans.map((plan) => (
              <div
                key={plan.name}
                className={`relative flex flex-col rounded-3xl p-8 border transition-all duration-300 ${
                  plan.isPopular
                    ? 'bg-[#0d1626] border-cyan-500/40 shadow-[0_0_40px_-10px_rgba(6,182,212,0.25)] md:-translate-y-3'
                    : 'bg-[#111625]/40 border-gray-900 hover:border-gray-700'
                }`}
              >
                {plan.isPopular && (
                  <span className="absolute -top-3.5 left-1/2 -translate-x-1/2 px-4 py-1 bg-gradient-to-r from-cyan-400 to-teal-400 text-[#070a13] text-[11px] font-extrabold uppercase tracking-wider rounded-full shadow-lg shadow-cyan-500/25">
                    Most Popular
                  </span>
                )}

                <div className="space-y-2">
                  <h3 className="text-lg font-bold text-white">{plan.name}</h3>
                  <p className="text-xs text-gray-500 font-medium">{plan.subtitle}</p>
                  <p className="pt-2">
                    <span className="text-4xl font-extrabold text-white">{plan.price}</span>
                    <span className="text-sm text-gray-500 font-medium"> /month</span>
                  </p>
                </div>

                <ul className="space-y-3 mt-8 flex-1">
                  {plan.features.map((feature) => (
                    <li key={feature} className="flex items-start gap-3 text-sm text-gray-300">
                      <span className="mt-0.5 w-5 h-5 rounded-full bg-cyan-950 border border-cyan-500/30 flex items-center justify-center shrink-0">
                        <Check size={12} className="text-cyan-400" />
                      </span>
                      {feature}
                    </li>
                  ))}
                </ul>

                <button
                  onClick={() => navigate('/subscription')}
                  className={`mt-8 w-full px-6 py-3.5 font-bold rounded-xl transition-all active:scale-[0.98] ${
                    plan.isPopular
                      ? 'bg-gradient-to-r from-cyan-400 to-teal-400 text-[#070a13] shadow-lg shadow-cyan-500/20 hover:opacity-95'
                      : 'bg-gray-900/60 border border-gray-800 text-white hover:bg-gray-900 hover:border-gray-700'
                  }`}
                >
                  Start Free Trial
                </button>
              </div>
            ))}
          </div>

          <p className="text-center text-xs text-gray-600 font-medium">
            Need more volume? Call-minute, SMS, and email add-ons are available on every plan.
          </p>
        </div>
      </section>

      {/* Trust strip */}
      <section className="py-14 border-t border-gray-950 bg-[#0a0e1a]/60">
        <div className="max-w-5xl mx-auto px-6 grid grid-cols-1 sm:grid-cols-3 gap-8 text-center">
          <div className="flex flex-col items-center gap-3">
            <div className="w-11 h-11 rounded-2xl bg-gray-900 border border-gray-800 flex items-center justify-center text-cyan-400">
              <Lock size={20} />
            </div>
            <p className="text-sm font-bold text-white">Private by Design</p>
            <p className="text-xs text-gray-500 leading-relaxed max-w-[240px]">
              Encrypted data, secure integrations, and role-based access control for your whole team.
            </p>
          </div>
          <div className="flex flex-col items-center gap-3">
            <div className="w-11 h-11 rounded-2xl bg-gray-900 border border-gray-800 flex items-center justify-center text-cyan-400">
              <Users size={20} />
            </div>
            <p className="text-sm font-bold text-white">Built for Teams</p>
            <p className="text-xs text-gray-500 leading-relaxed max-w-[240px]">
              Owner, manager, and staff roles with a shared inbox — everyone sees what they need to.
            </p>
          </div>
          <div className="flex flex-col items-center gap-3">
            <div className="w-11 h-11 rounded-2xl bg-gray-900 border border-gray-800 flex items-center justify-center text-cyan-400">
              <CalendarClock size={20} />
            </div>
            <p className="text-sm font-bold text-white">Up & Running in Minutes</p>
            <p className="text-xs text-gray-500 leading-relaxed max-w-[240px]">
              Connect your channels, forward your number, and your AI receptionist is on duty.
            </p>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-24 md:py-32 relative bg-gradient-to-b from-[#0a0e1a] to-[#070a13] border-t border-gray-950">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-96 h-96 bg-cyan-500/5 rounded-full blur-[100px] pointer-events-none -z-10" />

        <div className="max-w-4xl mx-auto px-6 text-center space-y-8">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-cyan-500/30 bg-cyan-950/20 text-cyan-400 text-xs font-semibold uppercase tracking-wider mx-auto">
            <Megaphone size={12} /> 7-Day Free Trial
          </div>
          <h2 className="text-3xl sm:text-5xl font-extrabold text-white tracking-tight leading-tight">
            Your AI team member starts today.
          </h2>
          <p className="text-lg md:text-xl text-gray-400 max-w-2xl mx-auto font-normal leading-relaxed">
            Calls answered. Messages replied. Invoices paid. Documents signed. Posts published.
            All while you focus on the work only you can do.
          </p>
          <div className="pt-4">
            <TrialButton />
          </div>

          <div className="pt-6 space-y-3">
            <p className="text-xs font-semibold uppercase tracking-wider text-gray-600">Also coming to mobile</p>
            <div className="flex flex-wrap items-center justify-center gap-3">
              <StoreBadge icon={Apple} eyebrow="Download on the" label="App Store" />
              <StoreBadge icon={Play} eyebrow="GET IT ON" label="Google Play" />
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-gray-950 bg-[#05070d] py-16">
        <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-8">

          <div className="flex items-center gap-2">
            <img src={logoMark} alt="GoCustify logo" className="w-8 h-8 rounded-lg" />
            <span className="text-lg font-bold text-white">GoCustify</span>
          </div>

          <div className="flex flex-wrap items-center justify-center gap-6 md:gap-8 text-xs font-semibold text-gray-500">
            <a href="#journey" className="hover:text-gray-300 transition-colors">How It Works</a>
            <a href="#features" className="hover:text-gray-300 transition-colors">Features</a>
            <a href="#pricing" className="hover:text-gray-300 transition-colors">Pricing</a>
            <button type="button" onClick={() => navigate('/privacy-policy')} className="hover:text-gray-300 transition-colors">Privacy Policy</button>
            <button type="button" onClick={() => navigate('/sms-messaging-policy')} className="hover:text-gray-300 transition-colors">SMS Messaging Policy</button>
            <button type="button" onClick={() => navigate('/terms-and-conditions')} className="hover:text-gray-300 transition-colors">Terms & Conditions</button>
          </div>

          <p className="text-xs text-gray-600 text-center md:text-right">
            © 2026 GoCustify. AI-powered business automation for modern teams.
          </p>
        </div>
      </footer>

    </div>
  );
}
